### ISSUE TITLE
Footer misalignment when any text.Color is used in the Transformer

### ISSUE THREAD

**Issue by xitonix** [jedib0t/go-pretty#112]
**Describe the bug**
First of all, thank you so much for the amazing work @jedib0t 🏅 

I appears that using any `text.Color` formatter in the footer transformer breaks the layout. To be clear, the snippet below is simplified. I don't only need to colorise the whole footer. It needs to be conditionally formatted and that's why I'm using Transformers. 

**To Reproduce**
```
t := table.NewWriter()
t.SetStyle(table.StyleRounded)
t.SetOutputMirror(os.Stdout)
t.AppendHeader(table.Row{"First Name", "Last Name", "Salary"})

nameTransformer := text.Transformer(func(val interface{}) string {
   // Replacing this with fmt.Sprint(val) will solve the problem
   // But no formatting obviously!    
   return text.Bold.Sprint(val)
})

t.SetColumnConfigs([]table.ColumnConfig{
 {
	Name:              "Salary",
	Transformer:       nameTransformer,
	TransformerFooter: nameTransformer,
   },
})
t.AppendRows([]table.Row{
	{"Arya", "Stark", 3000},
	{"Jon", "Snow", 2000},
})
t.AppendSeparator()
t.AppendFooter(table.Row{"", "Total", 10000})
t.Render()
```

**Expected behavior**
The table should be properly aligned but this is what I see:

**Screenshots**
![image](https://user-images.githubusercontent.com/4546371/81761656-d6423c80-950d-11ea-9f9c-fd5ca7b25646.png)

**Software (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - GoLang Version: go1.14.2 darwin/amd64

**Comment by jedib0t** [comment]
Hey thanks for the compliments. My first open-source project, so I'm a little attached to it at the moment. 😄 

Found the bug b.t.w, your custom transformer is returning Bold text which looks like this with escape sequences: `[1m10000[0m`. The code then applies the style's formatter for the footer which is `text.FormatUpper` which converts the case-sensitive escape sequences too: `[1M10000[0M`. And this is basically garbage to the terminal emulator. I'm guessing the same bug should be show up in headers too if you use `TransformerHeader`.

I'll fix it this week. 👍

But if you can't wait for a fix until then, you can use this workaround before calling `t.Render()`:
```golang
    t.Style().Format.Footer = text.FormatDefault
```

**Comment by jedib0t** [comment]
@xitonix Thanks for reporting the bug btw. I appreciate it!

**Comment by xitonix** [comment]
Thank you for getting back to me so quickly @jedib0t . I tried the workaround you suggested and it worked perfectly. Thanks a lot mate.

Btw, what I said was not just a complement! That's a beautiful piece of work buddy. Good on ya!

**Comment by jedib0t** [comment]
Hey @xitonix the latest code in `master` branch has the fix (https://github.com/jedib0t/go-pretty/commit/d24d83bda5d4e7ee242a5e73cb6e66ceb18cc2c6, https://github.com/jedib0t/go-pretty/commit/8b58fbaf3b31b8329524f6b6018e3352b569bf9f). I'll cut a tag by end of week.

Out of curiosity, do you use `go mod` or `dep` for dependency management? I transitioned to `go mod` some time back, but I figured recently that I've not done major versioning the way `go mod` likes it. I can fix that, but that may break `dep` support.

**Comment by xitonix** [comment]
Hey mate. I do use go mod, but because of the reason you mentioned yourself above, it cannot pick up the right version unfortunately. But I don't really understand why go mod always fetches v4.3.0 while you don't even have a v4 branch, even though I explicitly asked for v5.0.1! This is what appears in my `go.mod` file after I run:

`go get github.com/jedib0t/go-pretty@v5.0.1`

```
github.com/jedib0t/go-pretty v4.3.0+incompatible
```

**Comment by jedib0t** [comment]
Yeah I have a fix in the pipeline for this. Give me a day or two. See if you can use the commit hash instead of the version tag.
