### ISSUE TITLE
Add option to not escape HTML for table

### ISSUE THREAD

**Issue by legate** [jedib0t/go-pretty#119]
I'd like to render HTML tables with links. However it seems the HTML is escaped, so this:

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"Item", "Link"})
	t.AppendRow(table.Row{"Foo", `<a href="http://example.com">Go to item</a>`})
	t.RenderHTML()

Results in this:

```
<table class="go-pretty-table">
  <thead>
  <tr>
    <th>Item</th>
    <th>Link</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Foo</td>
    <td>&lt;a href=&#34;http://example.com&#34;&gt;Go to item&lt;/a&gt;</td>
  </tr>
  </tbody>
</table>
```

Is there a way to disable the HTML escaping?

**Comment by jedib0t** [comment]
Oh wow. Will provide some way in the interface to stop escaping the text. Sorry for the bug.

Didn’t think this library would be primarily used to render HTML more than as a ASCII table renderer and didn’t pay enough attention/thought to it.

ETA for this to be fixed: a day or two.

**Comment by jedib0t** [comment]
@legate I've provided a new struct to control the HTML rendering as you like. To fix your specific use-case, you'd have to add the following line before calling `t.RenderHTML()`:
```golang
    t.Style().HTML.Escape = false
```

The current list of options and the defaults can be found here: https://github.com/jedib0t/go-pretty/blob/master/table/style.go#L683-L701. I will try to bring `RenderHTML` on par with `Render()` going forward (by supporting features like auto-merge, etc).

I've cut a new tag for you to use: https://github.com/jedib0t/go-pretty/releases/tag/v6.0.2
