### ISSUE TITLE
AppendSeparator | Method not available

### ISSUE THREAD

**Issue by distek** [jedib0t/go-pretty#121]
**Describe the bug**
package table not allowing use of `AppendSeparator()`
`t.AppendSeparator undefined (type table.Writer has no field or method AppendSeparator)`

I can see the method is still in the source, however.

**To Reproduce**
Use most recent branch of go-pretty
```
import () {
	"github.com/jedib0t/go-pretty/table"
}

func main() {
    ...
    t := table.NewWriter()
    (header and first row)
    t.AppendSeparator
    (row ...n)
    t.Render()
    ...
}
```

**Expected behavior**
Row separator to be printed.

**Screenshots**
n/a - unable to compile

**Software (please complete the following information):**
 - OS: Archlinux 5.6.13-arch1-1
 - GoLang Version: go version go1.14.3 linux/amd64

**Additional context**
Everything else from table appears to be functioning correctly.

**Comment by distek** [comment]
Update: I must be doing something wrong. The table demo works just fine when calling `table.NewWriter()` the same way.

**Comment by distek** [comment]
Ah, well then..

```
import {
	"github.com/jedib0t/go-pretty/v6/table"
}
```

the `/v6/` part of it was missing.
Never had to deal with that before.

Closing.

**Comment by jedib0t** [comment]
Yep, that is a new thing. Had to add the `/v6` in the path to make it compatible with `go mod`: https://github.com/jedib0t/go-pretty#a-note-about-v600-and-above-

**Comment by distek** [comment]
Good to know! Thanks!
