### ISSUE TITLE
Option to suppress empty columns

### ISSUE THREAD

**Issue by robertlacroix** [jedib0t/go-pretty#124]
**Is your feature request related to a problem? Please describe.**
It'd be great if there was a way to suppress columns that only have empty cells. I'm calling `AppendRow` from a loop and one of the columns is only populated in some cases and it'd be great if the whole column could be suppressed if none of the rows have any value for it.

**Describe the solution you'd like**
There are probably a lot of ways to address this, for example by marking a column as optional, or by being able to remove a column right before rendering.

**Describe alternatives you've considered**
I could make a two pass loop, first to determine if the column will have any values and then again to actually populate it, or probably some other workarounds, but it'd be more convenient if there was some built in way.

**Comment by jedib0t** [comment]
Hey. Sounds like a useful feature to have. Lemme look into it.

Just so you know, ColumnConfig has a Hidden flag that you can use to hide columns manually: https://github.com/jedib0t/go-pretty/blob/v6.0.3/table/config.go#L43-L46 --- what you are asking for here is an automated way to do it.

**Comment by robertlacroix** [comment]
Awesome, thanks for the enhancement!

**Comment by jedib0t** [comment]
@robertlacroix Please try using `table.SuppressEmptyColumns()`. I just cut a tag for you to use: https://github.com/jedib0t/go-pretty/releases/tag/v6.0.4

**Comment by robertlacroix** [comment]
Works great!! Thanks again, especially the quick turnaround
