### ISSUE TITLE
Support cell merging on a per cell basis with something like HTML's "colspan"

### ISSUE THREAD

**Issue by autarch** [jedib0t/go-pretty#127]
**Is your feature request related to a problem? Please describe.**

I'd like to display tables with more control over the exact placement of separators than auto-merge allows. For example, something like this:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
│ Failed test: 1 == 0                                                                           │
├──────┬─────────────────┬────┬─────────────────┬───────────────────────────────────────────────┤
│      │      ACTUAL     │    │      EXPECT     │                                               │
│ PATH │ TYPE   │ VALUE  │ OP │ TYPE   │ VALUE  │ CALLER                                        │
├──────┼────────┴────────┴────┴────────┴────────┼───────────────────────────────────────────────┤
│ int  │                 │    │                 │ demo/demo_test.go@21 called detest.(*D).Equal │
│      │ int    │ 1      │ == │ int    │ 0      │                                               │
└──────┴────────┴────────┴────┴────────┴────────┴───────────────────────────────────────────────┘
```

Note the extra separators on the line starting with the caller "demo/demo_test.go ...".

AFAICT, there's no way to do this with auto-merge.

**Describe the solution you'd like**

I think the best way to do this would be to allow more explicit control over cell merging, with something like HTML's `colspan`. To do this in the current API I think you'd need to add something to the existing `RowConfig{}` struct. But a much nicer API would probably require creating some sort of `Cell{}` struct that could have a `colspan` (and it would also allow for much more granular control of horizontal alignment as a bonus).

**Describe alternatives you've considered**

I'm not sure there is any alternative to this, other than just accepting that I cannot do this. FWIW, I started off implementing my own table package which _does_ do this, but it doesn't do cell wrapping, so I was looking at alternatives. If you're curious you can see my WIP at https://github.com/houseabsolute/detest/tree/master/internal/table

(As an aside, I'm now realizing that go-pretty doesn't do cell wrapping either, just truncation, so I'll probably keep working on my package, but I'd love to offload this work to something that other people are already using!)

**Comment by jedib0t** [comment]
For supporting the feature requested in https://github.com/jedib0t/go-pretty/issues/94, I did start working on a `Cell{}` implementation, but I never got around to finishing it as I had to redo a lot of code. I'll try going back to it as soon as I find a good chunk of time.

BTW, `go-pretty` does do cell wrapping: https://github.com/jedib0t/go-pretty/blob/master/table/config.go#L64-L70 - you'd want to use `WidthMax`. Set up your own `WidthMaxEnforcer` if you want to do something other than `text.WrapText`.

**Comment by jedib0t** [comment]
For supporting the feature requested in https://github.com/jedib0t/go-pretty/issues/94, I did start working on a `Cell{}` implementation, but I never got around to finishing it as I had to redo a lot of code. I'll try going back to it as soon as I find a good chunk of time.

BTW, `go-pretty` does do cell wrapping: https://github.com/jedib0t/go-pretty/blob/master/table/config.go#L64-L70 - you'd want to use `WidthMax`. Set up your own `WidthMaxEnforcer` if you want to do something other than `text.WrapText`.

**Comment by jedib0t** [comment]
Can you share your table rendering code you are using for the above? I'm wondering why you'd need the blank lines with separators like above... is it due to you not wanting to share private data here? Or is it because you feel every `ACTUAL` and `EXPECT` column should have a blank leading line in each row?

**Comment by autarch** [comment]
@jedib0t my table code is in https://github.com/houseabsolute/detest/tree/master/internal/table

**Comment by autarch** [comment]
> I'm wondering why you'd need the blank lines with separators like above... is it due to you not wanting to share private data here? Or is it because you feel every `ACTUAL` and `EXPECT` column should have a blank leading line in each row?

I think the example I shared probably doesn't have enough rows to answer this. Here's a few more involved examples.

```
┍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┑
│                                 Failed test: slice out of bounds                                 │
┝━━━━━━━┯━━━━━━━━━━━━━━┯━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┥
│       │    ACTUAL    │    │    EXPECT    │                                                       │
│ PATH  │ TYPE │ VALUE │ OP │ TYPE │ VALUE │                        CALLER                         │
├───────┼──────┴───────┴────┴──────┴───────┼───────────────────────────────────────────────────────┤
│ []int │                                  │ demo/demo_test.go@27 called detest.(*D).Slice         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [2]   │                                  │ demo/demo_test.go@32 called detest.(*SliceTester).Idx │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ int   │                                  │ demo/demo_test.go@32 called detest.(*D).Equal         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌┬╌╌╌╌╌╌╌┬╌╌╌╌┬╌╌╌╌╌╌┬╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│       │ int  │ 3     │ == │ int  │ 4     │                                                       │
┕━━━━━━━┷━━━━━━┷━━━━━━━┷━━━━┷━━━━━━┷━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┙
```

So the `PATH` column is showing the "path" through a data structure. The corresponding Go code is:

```go
func Test3(t *testing.T) {
	d := detest.New(t)
	d.Is(
		[]int{1, 2, 3},
		d.Slice(func(st *detest.SliceTester) {
			st.Idx(0, d.Equal(1))
			st.Idx(1, d.Equal(2))
			st.Idx(2, d.Equal(4))
			st.Idx(3, d.Equal(4))
		}),
		"slice out of bounds",
	)
}
```

The failure above is for the line `st.Idx(2, d.Equal(4))`. So the table tells you not just what wasn't equal, but how you got there. For a simple slice this is probably overkill, but for much more complex data structures it's quite helpful.

BTW, this is all shamelessly stolen from a really great Perl library, [Test2-Suite](https://metacpan.org/release/Test2-Suite).

**Comment by autarch** [comment]
Heh, now that I'm looking at the output from my own library I'm realizing it doesn't do the separators quite the way I want either, but I was able to fix it because I have the ability to do per-cell colspans.

```
┍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┑
│                                 Failed test: slice out of bounds                                 │
┝━━━━━━━┯━━━━━━━━━━━━━━┯━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┥
│       │    ACTUAL    │    │    EXPECT    │                                                       │
│ PATH  │ TYPE │ VALUE │ OP │ TYPE │ VALUE │                        CALLER                         │
├───────┼──────┴───────┼────┼──────┴───────┼───────────────────────────────────────────────────────┤
│ []int │              │    │              │ demo/demo_test.go@27 called detest.(*D).Slice         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ [2]   │              │    │              │ demo/demo_test.go@32 called detest.(*SliceTester).Idx │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ int   │              │    │              │ demo/demo_test.go@32 called detest.(*D).Equal         │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌┬╌╌╌╌╌╌╌┼╌╌╌╌┼╌╌╌╌╌╌┬╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│       │ int  │ 3     │ == │ int  │ 4     │                                                       │
┕━━━━━━━┷━━━━━━┷━━━━━━━┷━━━━┷━━━━━━┷━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┙
```

**Comment by jedib0t** [comment]
Thanks for the detailed info. Will try to get cracking on the `Cell{}` implementation. I think it is needed anyway if I've to make any more meaningful features on the table writer anyway.

**Comment by jedib0t** [comment]
Haven't been able to get to this yet. This would need a major rewrite of the table rendering logic and may not be worth the effort. Will keep this open for some more time, and if I don't make any meaningful progress, I may end up closing this.
