### ISSUE TITLE
Progressbar ETA when ShowOverallTracker(false)

### ISSUE THREAD

**Issue by nicocha30** [jedib0t/go-pretty#134]
**Is your feature request related to a problem? Please describe.**

ETA is not displayed when using *pw.ShowOverallTracker(false)*

**Describe the solution you'd like**

Add a ShowETA function to display the ETA when not using OverallTracker

Thanks!

Nicolas.

**Comment by jedib0t** [comment]
Hey @Nicocha30 ... can you try using the code in the `progressbar-eta` branch and let me know if this is what you want?

Ref.: https://github.com/jedib0t/go-pretty/tree/progressbar-eta

**Comment by nicocha30** [comment]
Hi @jedib0t !

Thanks a lot for accepting this feature!

It's great, however, can the ETA be displayed on the same line ?

I'm getting something like this:

```
Downloading /home/n.chatelain/Téléchargements/file.txt ... 98.17% [#################.] [1.05GB in 5.300808s]
                                [5s; ~ETA: 1s]
```

It would be better if printed on the same line:

```
Downloading /home/n.chatelain/Téléchargements/file.txt ... 98.17% [#################.] [1.05GB in 5.300808s] [5s; ~ETA: 1s]
```
Thanks,

Nicolas

**Comment by jedib0t** [comment]
Hey @Nicocha30 sorry I misunderstood your original request. I've pushed some additional commits. `ShowETA(true)` now toggles ETA for all individual trackers instead of showing the overall ETA in the overall tracker.

**Comment by nicocha30** [comment]
Wow, this is awesome. Thanks!
However, in some cases, the progress bar seems to be "blocked" (like a deadlock ?) at `SetValue`.
Only happens when ShowETA(true).

I used the following test code : 

```
package main

import (
	"github.com/jedib0t/go-pretty/v6/progress"
	"time"
)

func main(){
	pw := progress.NewWriter()
	pw.ShowOverallTracker(false)
	pw.ShowETA(true)
	pw.ShowTime(true)
	pw.ShowTracker(true)
	pw.ShowValue(true)
	pw.SetSortBy(progress.SortByPercentDsc)
	pw.SetStyle(progress.StyleDefault)
	pw.SetTrackerPosition(progress.PositionRight)
	pw.SetUpdateFrequency(time.Millisecond * 50)
	pw.Style().Colors = progress.StyleColorsExample
	defer pw.Stop()

	tracker := progress.Tracker{Message: "Downloading", Total: 1024*1024*1024, Units: progress.UnitsBytes}
	pw.AppendTracker(&tracker)
	go pw.Render()

	read := int64(0)
	for {
		read += 10240
		tracker.SetValue(read)
		time.Sleep(5 * time.Microsecond)
		if read >= 1024*1024*1024 {
			break
		}
	}

	tracker.MarkAsDone()
	time.Sleep(100 * time.Millisecond)
}
```

**Comment by jedib0t** [comment]
Hey thanks for the code snippet. Was able to reproduce the issue 1 time out of 10. Will try to find the root-cause and fix the same.

Edit: @Nicocha30 can you please use the latest code? I think I've found and fixed the deadlock.

**Comment by nicocha30** [comment]
Works perfectly.

Thanks a lot, will definitely use this feature

**Comment by nicocha30** [comment]
Woops, reopening the issue. The progressbar is still blocking...

**Comment by nicocha30** [comment]
Hey @jedib0t , the progressbar is still blocking, do you have any idea why ?

**Comment by jedib0t** [comment]
Hey sorry for missing you last comment on this. Can you use the Increment interface instead of the SetValue interface and see if it still  blocks? I'll look into this when I find time.
