### ISSUE TITLE
If the title is longer than column 1 + 2, title wraps abnormally

### ISSUE THREAD

**Issue by Liurl21** [jedib0t/go-pretty#135]
If the title is longer than column 1 + 2,  the length of the title is the total length of the column, like this:
```
+---------+
| FixedBy |
| tesCach |
| ePrintS |
| tats    |
+-----+---+
| GET | 1 |
| NEW | 1 |
| REC | 1 |
+-----+---+

```
such title are not easy to read, we think the table should expand and not wrap title:
```
+--------------------------+
| FixedBytesCachePrintStats|
+----------------------+---+
|         GET          | 1 |
|         NEW          | 1 |
|         REC          | 1 |
+----------------------+---+
```

code used to generate the table:

```
t := table.NewWriter()
t.SetOutputMirror(os.Stdout)
t.SetTitle("FixedBytesCachePrintStats")
t.AppendRows([]table.Row{{"GET", 1},
	{"NEW", 1},
	{"REC", 1}})
t.Render()
```

**Comment by jedib0t** [comment]
Hey. Auto-managing the size of one or more columns automatically will break formatting and backward compatibility. I'd recommend you use SetColumnConfig to set one of the Column's minimum width as needed to adjust for the title.

**Comment by Liurl21** [comment]
> Hey. Auto-managing the size of one or more columns automatically will break formatting and backward compatibility. I'd recommend you use SetColumnConfig to set one of the Column's minimum width as needed to adjust for the title.

ok, thank you.

**Comment by jedib0t** [comment]
I'll leave this open to see if I can provide some options around the Title to do stuff like this.

**Comment by vicentepinto98** [comment]
Hello, I faced the same issue. 

Some options to extend the title would be appreciated.
