### ISSUE TITLE
Strange padding issue when rendering `%` in a column

### ISSUE THREAD

**Issue by mwarkentin** [jedib0t/go-pretty#136]
**Describe the bug**
Hello, I'm working on a PR in another project which is using this library: https://github.com/rocketmiles/aws-cct/pull/9

I'm attempting to add a column which is a percent value, so I'm also adding `%` as part of the `fmt.Sprintf` call: https://github.com/rocketmiles/aws-cct/pull/9/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R175

The first issue I came across is that I seemed to need to "double escape" the percentage sign (`%%%%` instead of `%%` as I expected based on Go docs). The second is that the padding on the column seems to think that there are 2 characters added instead of one (note the border is collapsed by 1 char):

```
+-------------------------------------------------+-------------+-------------+------------+---------------+
| SERVICE                                         | 2020-09-01  | 2020-10-01  | DELTA      | DELTA PERCENT |
+-------------------------------------------------+-------------+-------------+------------+---------------+
| Amazon Macie                                    |       $0.00 |      $56.40 |     $56.40 |       +Inf%  |
| Amazon Comprehend                               |       $0.00 |       $0.02 |      $0.02 |       +Inf%  |
| Amazon EC2 Container Service                    |      $64.22 |     $151.43 |     $87.21 |      135.8%  |
```

**To Reproduce**
* Check out code from PR: https://github.com/rocketmiles/aws-cct/pull/9/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R175
* Run `go build && ./aws-cct` (requires valid AWS creds in your config)

If there's nothing immediately obvious about this bug report or if you think it might be some other part of my system I can try to make a more specific reproduction.

**Expected behavior**
* Escape `%` normally: `%%` instead of `%%%%`
* Table padding is calculated correctly

**Screenshots**
![](https://s3.amazonaws.com/mwarkentin-snaps/ec2-userconvox-prod--i-004051e899b8bf2e5_2020-11-11_21-05-34.png)

**Software (please complete the following information):**
 - OS: MacOS 10.15.7
 - go1.15.3 darwin/amd64

**Additional context**
None

**Comment by mwarkentin** [comment]
Removed all formatting (`Align: text.AlignRight`) from the column and confirmed the issue still exists: 

```
+-------------------------------------------------+-------------+-------------+------------+---------------+
| SERVICE                                         | 2020-09-01  | 2020-10-01  | DELTA      | DELTA PERCENT |
+-------------------------------------------------+-------------+-------------+------------+---------------+
| Amazon Macie                                    |       $0.00 |      $56.40 |     $56.40 | +Inf%        |
| Amazon Comprehend                               |       $0.00 |       $0.02 |      $0.02 | +Inf%        |
```

**Comment by mwarkentin** [comment]
I also tried forcing the width of the column, no dice:

```
+-------------------------------------------------+-------------+-------------+-------------+--------------------------------------+
| SERVICE                                         | 2020-01-01  | 2020-02-01  | DELTA       | DELTA PERCENT                        |
+-------------------------------------------------+-------------+-------------+-------------+--------------------------------------+
| Amazon Athena                                   |       $0.00 |       $0.75 |       $0.75 |                               +Inf% |
| AWS Amplify                                     |       $0.16 |      $12.84 |      $12.68 |                             7925.0% |
| CodeBuild                                       |      $26.69 |      $39.31 |      $12.62 |                               47.3% |
```

**Comment by mwarkentin** [comment]
Here's what I get if I only escape the `%` once:

```
+-------------------------------------------------+-------------+-------------+-------------+--------------------------------------+
| SERVICE                                         | 2020-01-01  | 2020-02-01  | DELTA       | DELTA PERCENT                        |
+-------------------------------------------------+-------------+-------------+-------------+--------------------------------------+
| Amazon Athena                                   |       $0.00 |       $0.75 |       $0.75 |                                +Inf%!|(MISSING)
| AWS Amplify                                     |       $0.16 |      $12.84 |      $12.68 |                              7925.0%!|(MISSING)
| CodeBuild                                       |      $26.69 |      $39.31 |      $12.62 |                                47.3%!|(MISSING)
```

**Comment by mwarkentin** [comment]
Got the following suggestion from someone at work:

> This looks like a bug deep in their layout code, you don't need to double escape the % for a straight-up string (eg https://play.golang.org/p/tm1O1efrZl2). I'd guess that somewhere they're passing the string literal you're providing through Sprintf again to get that result (see https://play.golang.org/p/chKNNAgARlq vs https://play.golang.org/p/fy5_pfr1-qR)

> The padding  issue I'd imagine is because in the same pass they're just taking the len() of the string, which would be something like 7.55%% at that point and then losing the escape character when it passes through another layer of printing

**Comment by jedib0t** [comment]
First I apologize for the late reply. For whatever reason my Mail client and GitHub app both did not alert me about this new issue. 😞

Yes the code does indeed do a fmt.Sprint and the len() may be accounting for the double % symbols. Lemme try to reproduce the issue today and work on a possible fix.

**Comment by mwarkentin** [comment]
No worries, thanks for looking into it!

**Comment by jedib0t** [comment]
Hey @mwarkentin ... I finally got around to looking at this. Sorry for the delay. :(

I wasn't able to reproduce the issue with the following code:
````golang
package main

import (
	"fmt"

	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/jedib0t/go-pretty/v6/text"
)

func main() {
	tw := table.NewWriter()
	tw.AppendHeader(table.Row{"#", "Testing Percentages"})
	tw.AppendRow(table.Row{101, fmt.Sprintf("Test%s%%", "Percent")})
	tw.AppendRow(table.Row{102, fmt.Sprintf("TestP%s%%", "ercent")})
	tw.AppendRow(table.Row{103, fmt.Sprintf("TestPe%s%%", "rcent")})
	tw.AppendRow(table.Row{104, fmt.Sprintf("TestPer%s%%", "cent")})
	tw.AppendRow(table.Row{105, fmt.Sprintf("TestPerc%s%%", "ent")})
	tw.SetColumnConfigs([]table.ColumnConfig{
		{Number: 2, Align: text.AlignRight},
	})
	tw.SortBy([]table.SortBy{
		{Number: 1, Mode: table.Asc},
	})

	fmt.Println(tw.Render())
}
```

Am I missing something?

**Comment by jedib0t** [comment]
Hey @mwarkentin ... do you have some time to get back with more info?

I tried to stick as close to your table generation code as possible with this new code sample:
```golang
package main

import (
	"fmt"
	"math"

	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/jedib0t/go-pretty/v6/text"
	"github.com/leekchan/accounting"
)

func main() {
	zero := float64(0.0)
	data := []float64{
		1.1,
		2.2,
		3.3,
		4.4,
		5.5,
		6.6 / zero * 100,
	}

	for _, formatStr := range []string{"%s%%%%", "%s%%"} {
		total := float64(0)
		tw := table.NewWriter()
		tw.AppendHeader(table.Row{"#", "Testing Percent"})
		for idx, v := range data {
			tw.AppendRow(table.Row{
				idx + 1, fmt.Sprintf(formatStr, accounting.FormatNumber(v, 1, "", ".")),
			})
			if v > 0 && v != math.Inf(+1) {
				total += v
			}
		}
		tw.AppendFooter(table.Row{
			"", fmt.Sprintf(formatStr, accounting.FormatNumber(total/float64(len(data)), 1, "", ".")),
		})
		tw.SetCaption("Format String: %#v", formatStr)
		tw.SetColumnConfigs([]table.ColumnConfig{
			{Name: "Testing Percent", Align: text.AlignRight, AlignFooter: text.AlignRight},
		})

		fmt.Printf("%s\n\n", tw.Render())
	}
}
```
Output:
```
+---+-----------------+
| # | TESTING PERCENT |
+---+-----------------+
| 1 |           1.1%% |
| 2 |           2.2%% |
| 3 |           3.3%% |
| 4 |           4.4%% |
| 5 |           5.5%% |
| 6 |          +Inf%% |
+---+-----------------+
|   |           2.8%% |
+---+-----------------+
Format String: "%s%%%%"

+---+-----------------+
| # | TESTING PERCENT |
+---+-----------------+
| 1 |            1.1% |
| 2 |            2.2% |
| 3 |            3.3% |
| 4 |            4.4% |
| 5 |            5.5% |
| 6 |           +Inf% |
+---+-----------------+
|   |            2.8% |
+---+-----------------+
Format String: "%s%%"
```

**Comment by mwarkentin** [comment]
@jedib0t let me see if I can take a look tomorrow at the reproduction

**Comment by jedib0t** [comment]
Closing it for now. Please reopen when you have more data. Thanks!
