### ISSUE TITLE
Hide columns I don't want to render

### ISSUE THREAD

**Issue by gianarb** [jedib0t/go-pretty#137]
Hello! Thank you for this library

**Describe the solution you'd like**

I would like to hide columns from a pre-populated table when I render it.

**Describe alternatives you've considered**

I can restructure my code to dynamically return headers and data but it looks more complicated compared with hiding columns and render time. I am not really scared about the wasted memory consumed by hidden values at the moment.

**Additional context**

I am writing a CLI and in order to get consistency as part of the code itself, the Get command is only one for all the resources I support. it means that I accept from the outside a function that returns the data I want `[]interface{}`,  a list of headers `[]string` and the function capable of converting a single row from the retrieve `data` into a `table.Row`.

I would like to add a feature to my Get command that only shows a sub of information.

**Comment by jedib0t** [comment]
This feature is already supported. Check out this unit test to see his to do it: https://github.com/jedib0t/go-pretty/blob/9875be5d373667c8494725ef2ba6e4974069d72e/table/render_test.go#L760

**Comment by gianarb** [comment]
This is awesome! Thanks a lot
