### ISSUE TITLE
Indeterminate Progress bar

### ISSUE THREAD

**Issue by ptxmac** [jedib0t/go-pretty#142]
**Is your feature request related to a problem? Please describe.**

I have a tool which performs several operations where the total is unknown. I still use a progress bar to indicate that something is happening, but it would be nice to have a mode where the progressbar indicate that its length is unknown.

**Describe the solution you'd like**

Similar to how `pv` works with a unknown length, it will just show the speed and have a little widget flying back'n'forth in the progress area

```
 [....<=>............] [34 in 3.504094s] ... Fetching ...
```

**Describe alternatives you've considered**
The current progressbar works, but it gives the user a sense that no progress is happening since it will always show 0%

**Additional context**
For reference, my needs come from having 10 parallel workers that each work on the same list of input. I have a master tracker for the total number of completed work, but I also have one for each worker - this way I can have a progressbar with a message for each piece of work currently being worked on:

```
99.71% [#################.] [680 in 3.50413s] ... Total
 0.00% [..................] [34 in 3.504094s] ... Fetching aaa
 0.00% [..................] [34 in 3.504095s] ... Fetching bbb
 0.00% [..................] [34 in 3.504068s] ... Fetching ccc
 0.00% [..................] [34 in 3.50407s] ... Fetching ddd
```
Since all workers share the same pool of work, they can't know how many they will work on in total

**Comment by jedib0t** [comment]
Hey this would definitely be good to have. I think I've structured the code to be able to do this already. Will get to this when time permits. In the meantime if you want to contribute, feel free to do so with a PR.

**Comment by ptxmac** [comment]
I might take a stab at it - got any pointers for how it should be integrated?

**Comment by ptxmac** [comment]
It could either be a new setting on the tracker, or it could be a convention that if `Total = 0` (or if `Value > Total`) then it will automatically be shown as indeterminate

**Comment by jedib0t** [comment]
@ptxmac I've been able to make some progress on this request. Can you try using the code in the `progress-indeterminate` branch? For demo, you can run `go run ./cmd/demo-progress`. The last tracker will not have a Total set, and should behave the way you requested.

**Comment by ptxmac** [comment]
Awesome, it looks very close to what I was looking for.
I think the `%` field should be changed though, it doesn't make much sense to have `0.0%` at all times:
`Calculating Total   # 13 ...  0.0% [....<#>................] [42.25K in 898.624ms]`

**Comment by jedib0t** [comment]
Correct. Missed that. Will look into it.

Edit: @ptxmac I've fixed it via https://github.com/jedib0t/go-pretty/commit/5d123d19349cf68b23be2b17ceabc9f2e06cb850

**Comment by jedib0t** [comment]
Please note: there are three ready-made indeterminate tracker stylings for you to use:
```golang
pw.Style().Chars.Indeterminate = progress.IndeterminateIndicatorMovingBackAndForth("<#>", progress.DefaultUpdateFrequency/2) // default
pw.Style().Chars.Indeterminate = progress.IndeterminateIndicatorMovingRightToLeft("<#>", progress.DefaultUpdateFrequency/2)
pw.Style().Chars.Indeterminate = progress.IndeterminateIndicatorMovingLeftToRight("<#>", progress.DefaultUpdateFrequency/2)
```

I've also made it a function that can technically replace the entire progress bar... you could theoretically make it look like Pac-Man gobbling up the dots if you want to for indeterminate cases. 😉 

Edit: two new styles you can use:
```golang
pw.Style().Chars.Indeterminate = progress.IndeterminateIndicatorDominoes(progress.DefaultUpdateFrequency/2)
pw.Style().Chars.Indeterminate = progress.indeterminateIndicatorPacMan(progress.DefaultUpdateFrequency/2)
```

**Comment by jedib0t** [comment]
@ptxmac I've just cut a new tag for you to use: https://github.com/jedib0t/go-pretty/releases/tag/v6.1.0

**Comment by ptxmac** [comment]
Perfect, thanks!
