### ISSUE TITLE
Unclear how to use SortBy

### ISSUE THREAD

**Issue by gennaro-tedesco** [jedib0t/go-pretty#149]
**Describe the bug**
I could not find documentation on `t.SortBy`

**To Reproduce**
The following 
```
t := table.NewWriter()
t.SetOutputMirror(os.Stdout)
t.AppendHeader(table.Row{"first", "second"})
t.SortBy("first")
...
```
generates `cannot use "first" (type string) as type []table.SortBy in argument to t.SortBy` (or anything else that is being passed, for that matter).

**Expected behavior**
I would like to be referred to documentation usage of the method `SortBy`. As [per here](https://github.com/jedib0t/go-pretty/blob/master/table/sort.go#L9) I expect `t.SortBy("column name")` to work, but apparently this is not the right grammar.

How is `SortBy` supposed to be called?

**Comment by jedib0t** [comment]
Hey @gennaro-tedesco! Thanks for bringing this to my attention. Will fix the documentation soon. 

For now you can refer to the unit tests to see how to use SortBy: https://github.com/jedib0t/go-pretty/blob/2843e11bf3a6fb5b34826430ec1b0dc870c5b195/table/sort_test.go#L36

**Comment by gennaro-tedesco** [comment]
Thank you for your quick reply! It seems that the correct grammar is, however,
```
t.SortBy([]table.SortBy{{Name: "first", Mode: table.AscNumeric}})
```
whereas the code in the test (namely without the full qualification `table.SortBy`) generates an exception of `undefined: SortBy`. I wonder if this is caused by the fact that the table is initialised in the test with
```
table := Table{}
```
rather than 
```
t := table.NewWriter()
```
? If so, what is the difference between these two constructors?

**Comment by jedib0t** [comment]
The unit-test was in the same package and so it didn't have to use the `table.` package qualifier.

`Table{}` returns the struct and `table.NewWriter()` returns an interface. Both are functionally similar and you can use either to do the same.

However, if you want to unit-test your code without invoking the actual Table generation logic, you should use the interface and generate mocks using mockgen from the published interface. Please google for mockgen and its usage. This is one method of mocking and testing, and not the only method.

**Comment by gennaro-tedesco** [comment]
Thank you very much for your explanation! All is working fine now, this issue can be closed!

**Comment by jedib0t** [comment]
👍🏽 will close once I fix the documentation to indicate how to use SortBy.
