### ISSUE TITLE
increase row distance (padding)

### ISSUE THREAD

**Issue by gennaro-tedesco** [jedib0t/go-pretty#169]
**Describe the bug**

Apologies if this is documented and I could not find it: I would like to increase distance between consecutive rows, namely allow for bigger padding between one row and the other.

**To Reproduce**

Looking at [these properties](https://github.com/jedib0t/go-pretty/blob/11849e40fe2d5c5e0c68bf6cbbb803a93e524321/table/table.go#L27) it seems only `allowedRowLength` is defined, likewise I could not find an equivalent of `t.SetColumnConfig` for rows. Moreover [box styles](https://github.com/jedib0t/go-pretty/tree/main/table#roll-your-own-style) only allow for `PaddingLeft/Right` and I could not find a similar entry for "row up/down".

**Expected behavior**

Does such option exist at all and what would you recommend in alternative?

**Comment by jedib0t** [comment]
At the moment, there is no way to increase the "padding"/distance between consecutive rows. You may want to just introduce newlines in your text to introduce an artificial empty line.

**Comment by gennaro-tedesco** [comment]
I see, thank you for looking into it!
