### ISSUE TITLE
Print rows one by one and incrementally

### ISSUE THREAD

**Issue by anvari1313** [jedib0t/go-pretty#184]
I'm writing a CLI application that subscribes on a channel (let's say a nats subject) and I want to print the received message in a table. But I don't know how to print just a new row and not the whole table. My problem is every time I call the `Render` method of a table, it prints all of the rows of the table and if I don't call it, nothing is shown.

**Comment by jedib0t** [comment]
Hey @anvari1313 sorry for the obscenely late response. Got busy with other things IRL.

Unfortunately, the above isn't an easy one to implement, since the row being added could alter the layout of the table (for ex. if one column has a longer length in the new row than all the previous rows).
