### ISSUE TITLE
set witdth of Cols based on col number

### ISSUE THREAD

**Issue by vijayrajah** [jedib0t/go-pretty#185]
**Is your feature request related to a problem? Please describe.**
While printing table without row headers, it seems it is not possible to set the col width.

**Describe the solution you'd like**
Can we not use the column number and set the width?

**Describe alternatives you've considered**
I have had to set row headers, just to set the width

**Comment by jedib0t** [comment]
Have you tried using the SetColumnConfigs function? Can you provide an example where you see it not working?

**Comment by jedib0t** [comment]
Closing due to lack of response.
