### ISSUE TITLE
If string contains 'á' character, it will not be aligned.

### ISSUE THREAD

**Issue by qiuyi21** [jedib0t/go-pretty#186]
**Describe the bug**
If string contains 'á' character, it will not be aligned.

**Comment by jedib0t** [comment]
Aligning Unicode characters does not work 100% of the time. I'll see if there is any update to the library I use to measure width of such characters.

**Comment by jedib0t** [comment]
Hey @qiuyi21 --- I updated the dependencies and cut a new tag. Can you check the alignment with v6.2.5?
