### ISSUE TITLE
Shorten time output value in progress bar

### ISSUE THREAD

**Issue by Blesmol** [jedib0t/go-pretty#188]
Hi,

The progress bar allows to display the elapsed time for a tracker. However, the time is currently displayed with lots of digits after the decimal point:
```
19.9% [####...................] [254 in 52.349705s; ~ETA: 3m43s]
58.4% [#############..........] [751 in 4m25.041613s; ~ETA: 3m12s]
```

It would be great if one could specify how many digits after the decimal point should be displayed, perhaps with a default of something between 0 and 2. After all, most times this should be totally sufficient.

Thanks & keep up the great work!

**Comment by Blesmol** [comment]
Ok, nevermind... only took a little bit longer until I found out how this can be done already:
```
myProgressWriter.Style().Options.TimeInProgressPrecision = time.Second
```
So will close this issue again... :)

**Comment by jedib0t** [comment]
👍
