### ISSUE TITLE
Line outputted in between, breaks the display.  Ideally default StdOut should be changed.

### ISSUE THREAD

**Issue by ykoehler** [jedib0t/go-pretty#195]
**Is your feature request related to a problem? Please describe.**
In my code, if an error occurs, there may be some output on the stdout.  Using go-pretty, what happens is that on the next render, we go up and re-write that line and it hides it.

What would be perfect, would be for go-pretty to change the default stdout when rendering is initially started, then render its graph and either allow for the original stdout to out in a file or to be emitted after the rendering (or before).

So that for example if a task emits a line such as "Error occured" the display looks like:

Error occurred
tracker 
tracker

or

tracker
tracker
Error occurred

Right now the string is totally overwritten and it then makes it hard to understand what really happened.  Like if I didn't want my program to emit on Stdout, but there is some case left, finding them would be easier this way.

**Comment by jedib0t** [comment]
Hey!

Thanks for the report. I've added a new interface `Log` in the Progress Writer interface that you can use to log additional messages that show up in the middle of progress tracking.

Sample log:
```
$ go run ./cmd/demo-progress --rnd-logs
Tracking Progress of 13 trackers ...

Calculating Total   #  1 ... done! [3.25K in 501ms]
Calculating Total   #  2 ... done! [6.50K in 501ms]
Downloading File    #  3 ... done! [9.75KB in 501ms]
Transferring Amount #  4 ... done! [$26.00K in 1.001s]
Transferring Amount #  5 ... done! [£32.50K in 1s]
Downloading File    #  6 ... done! [58.50KB in 1.5s]
[INFO] done with 6 trackers
Calculating Total   #  7 ... done! [91.00K in 2.001s]
Transferring Amount #  8 ... done! [$130.00K in 2.501s]
Downloading File    #  9 ... done! [204.75KB in 3.5s]
[INFO] done with 9 trackers
Transferring Amount # 10 ... done! [£260.00K in 4.001s]
Calculating Total   # 11 ... done! [357.50K in 5.001s]
Transferring Amount # 12 ... done! [$468.00K in 6.001s]
[INFO] done with 12 trackers
Calculating Total   # 13 ... done! [549.25K in 6.501s]

All done!
```

I've cut a tag too: https://github.com/jedib0t/go-pretty/releases/tag/v6.3.0

**Comment by ykoehler** [comment]
Hi, this is nice, but wish the whole stdout was somehow "redirected" instead, will try to find a way for it.

**Comment by jedib0t** [comment]
@ykoehler Have you tried the `SetOutputWriter` method? You can set up your own 'Writer' which will receive the raw text being rendered.
