### ISSUE TITLE
The "overall" ETA is always displayed even if ShowETA is false.

### ISSUE THREAD

**Issue by ykoehler** [jedib0t/go-pretty#196]

**Comment by jedib0t** [comment]
Sorry for no updates on this for so long. I'm trying to solve this without complicating the interfaces. Will share progress in a few days.

**Comment by ykoehler** [comment]
No rush here, once my tool is complete, I will see if I can help with some of my enh  request.

**Comment by jedib0t** [comment]
Hey @ykoehler - fix is available in https://github.com/jedib0t/go-pretty/releases/tag/v6.3.1
