### ISSUE TITLE
Need more than done/fail, add custom ones.

### ISSUE THREAD

**Issue by ykoehler** [jedib0t/go-pretty#198]
The MarkAsDone/MarkAsErrored are nice, but we need custom ones, such as "canceled", "aborted" "skipped" or "interrupted", etc.

Maybe a MarkAsErrored(string) would be useful.

**Comment by jedib0t** [comment]
This was brought up in an earlier issue, and my stance on this hasn't changed.

The progress tracker doesn't and shouldn't care about the "status variant" of the activity it is tracking. The client can use colors, or message formatting to convey this aspect of the task. If we go down the route of supporting all these custom statuses, there will be no end in sight and the interface would've mutated and be complex for very little benefit.

**Comment by ykoehler** [comment]
Color is certainly not a good enough solution, as there is no way to provide a "legend" to the end-user of what those mean, and the word fail in many colors does't look like a normal behavior, it looks more like a bug in the software.  I am unclear what is meant here by message formatting, can you point me to an example?

**Comment by jedib0t** [comment]
Originally MarkAsDone was the only supported status. MarkAsErrored was something I was not happy in implementing, as all it does is change the way the tracker is displayed by using a different [status string](https://github.com/jedib0t/go-pretty/blob/main/progress/style.go#L168) and [color](https://github.com/jedib0t/go-pretty/blob/main/progress/style.go#L138).

This could instead be done by just changing the message of the Tracker using the [Tracker.UpdateMessage(...)](https://github.com/jedib0t/go-pretty/blob/main/progress/tracker.go#L155) interface. I get that the status string cannot be changed here, and will look at a solve for it, but this interface should cover other use-cases.
