### ISSUE TITLE
Dynamic column creation for table rows

### ISSUE THREAD

**Issue by patrick-hermann-sva** [jedib0t/go-pretty#201]
hi!

let me start w/ my running code (the tables are looking great, thank you so much for your work!)

for creating the table rows i'm using a loop to iterate over a map w/ my custom type map[string]*Service. works great. 
```
	for k := range serviceList {

		t.AppendRows([]table.Row{
			{serviceList[k].Name, serviceList[k].Url, serviceList[k].Ip_addr, serviceList[k].Runs_on, serviceList[k].Description},
		})
	}
```

but now i want to print another custom struct/type and would like to fill the table/rows in a dynamic way. instead of doing object[x].field for the columns i would like to do this dynamically.  how is this possible? for example i can fille a []string with all fields dynamically but cannot assign it to a new row (to be recognized as unique columns). is this possible in any way?

**Comment by jedib0t** [comment]
Maybe you can use something like this:
```golang
	tw := table.NewWriter()

	strSlice := []string{"1", "2", "3", "4", "5"}
	var row table.Row
	for _, element := range strSlice {
		row = append(row, element)
	}
	tw.AppendRow(row)
```

**Comment by patrick-hermann-sva** [comment]
yes this worked out great!! thank you very much for your great work!
