### ISSUE TITLE
SetTitle with SetStytle has something wrong

### ISSUE THREAD

**Issue by idcdog** [jedib0t/go-pretty#204]
**Describe the bug**
hi , when use SetTitle  and SetStyle, the title rows  length is wrong
<img width="858" alt="image" src="https://user-images.githubusercontent.com/18034474/165901177-b1b2d90b-fd42-4e0e-9e7b-6d560946616e.png">

The code:
`package main

import (
	"github.com/jedib0t/go-pretty/v6/table"
	"os"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"#", "First Name", "Last Name", "Salary"})
	t.AppendRows([]table.Row{
		{1, "Arya", "Stark", 3000},
		{20, "Jon", "Snow", 2000, "You know nothing, Jon Snow!"},
	})
	t.SetTitle("SomeThing")
	t.AppendSeparator()
	t.AppendRow([]interface{}{300, "Tyrion", "Lannister", 5000})
	t.AppendFooter(table.Row{"", "", "Total", 10000})
	t.SetStyle(table.StyleBold)
	t.Render()
}
`

**Comment by jedib0t** [comment]
I was not able to reproduce this issue: https://goplay.tools/snippet/TUD1DWmuSw2

![image](https://user-images.githubusercontent.com/38574447/166133466-2765e652-cc12-4abd-95e1-59013f66820a.png)

What version of this module are you using? Are you on the latest published release?

**Comment by jedib0t** [comment]
Closing this for now due to lack of response from OP. Please re-open if you can reproduce this.

**Comment by idcdog** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/18034474/168996729-fbd7d281-325e-48d8-8881-b6911a3b24fc.png">

set LANG=en and run is ok
and if set LANG=zh_CN.UTF-8 , run is error.
😂
