### ISSUE TITLE
text.RuneCount should be called as text.RuneWidth

### ISSUE THREAD

**Issue by breezewish** [jedib0t/go-pretty#209]
**Is your feature request related to a problem? Please describe.**

The `RuneCount` function is actually implemented as calculating the rune **width** instead of rune **count**.

**Describe the solution you'd like**

Rename the function to `RuneWidth`.

**Comment by jedib0t** [comment]
Agreed that it is misnamed. Will rename it in a few days (but leave the original function marked as deprecated).

**Comment by jedib0t** [comment]
Fixed. Use tag https://github.com/jedib0t/go-pretty/releases/tag/v6.3.3 for the fix. Please note:
- text.RuneCount is marked as deprecated and will be removed in the next major release
- text.RuneWidthWithoutEscSequences is the replacement
