### ISSUE TITLE
Bottom line in box takes the FG color of the last line in table

### ISSUE THREAD

**Issue by jeanfrancoisgratton** [jedib0t/go-pretty#221]
**Description**
When changing the fore/background colors of rows in a table, the bottom line in the box enclosing the table takes that FG+BG value

**To Reproduce**
See code way below, with explanations

**Expected behavior**
Bottom border should be the same as the rest of the borders

**Screenshots**
![image](https://user-images.githubusercontent.com/19715390/185775509-3af1df7a-ebe8-4101-9108-3de66d592e81.png)

**Software (please complete the following information):**
 - OS: Linux (Ubuntu 22.04.01, fully updated)
 - GoLang Version 1.19 (manual install, not taking the .deb package from distro)

**Additional context**
A simple libvirtd client; a port of my Python3 current client. I want the "Running" VMs to be displayed in green, at the bottom of the list, but the bottom border keeps the last line's colors.

Here's my function that displays the VMs with their various states. The struct vmspecs holds all of the various VMs stats (I've snipped part of the code where not pertinent to issue)

```
func VM_List() {
	var vmspecs = collectInfo()

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader((table.Row{"ID", "VM name", "State", "vMemory", "vCPUs", "Snapshots", "Curr snapshot", "iface name", "IP address"}))
	for _, vmspec := range vmspecs {
		sID := ""
		if vmspec.viId > 0 && vmspec.viId < 10 {
			sID = fmt.Sprintf("000%d", vmspec.viId)
		
		<SNIP>
		
		t.AppendRow([]interface{}{sID, vmspec.viName, vmspec.viState, vmspec.viMem, vmspec.viCpu, vmspec.viSnapshot, vmspec.viCurrentSnapshot, vmspec.viInterfaceName, vmspec.viIPaddress})
	}
	t.SortBy([]table.SortBy{
		{Name: "ID", Mode: table.Asc},
		{Name: "VM name", Mode: table.Asc},
	})
	t.SetStyle(table.StyleBold)
	//t.Style().Options.DrawBorder = false
	//t.Style().Options.SeparateColumns = false
	t.Style().Format.Header = text.FormatDefault
	t.SetRowPainter(table.RowPainter(func(row table.Row) text.Colors {
		switch row[2] {
		case "Running":
			return text.Colors{text.BgBlack, text.FgHiGreen}
		case "Crashed":
			return text.Colors{text.BgBlack, text.FgHiRed}
		case "Blocked":
		case "Suspended":
		case "Paused":
			return text.Colors{text.BgHiBlack, text.FgHiYellow}
		}
		return nil
	}))
	t.Render()
}
```
This is my very first Go software; to learn a language you need your own project, right, so I'm porting my Python3 tool to Go, so bear with me if you see glaring coding errors.
For all I know, I might be missing something obvious in your package usage.

**Comment by jeanfrancoisgratton** [comment]
BTW, excellent lib. Features-packed, etc. It does things that would need 2-3 other libs to do. Quite impressed, and also, for a novice in Go, easily readable.

**Comment by jedib0t** [comment]
Thanks for the bug report and the compliments. Sounds like the Row Painter is being invoked for the separator/border incorrectly. I'll look into this tomorrow.

**Comment by jeanfrancoisgratton** [comment]
Looks like I've erased the compliment (I wanted to put it in the main report). You got it, that's all that matters.

No worry, I can live with the issue for now. Let me know if my report needs more info.

**Comment by jedib0t** [comment]
Hey @jeanfrancoisgratton --- the latest code in the main branch has the fix. If you can verify with it, I can cut a tag for you.

**Comment by jeanfrancoisgratton** [comment]
@jedib0t , this might seem a bit of a stupid question, but remember, this is about my first full-fledged GO software.

How do I go about removing earlier versions of `github.com/jedib0t/go-pretty/v6` from go.mod ?
I've erased go.{mod,sum} and $HOME/go/pkg/, go mod init vmman3, go mod tidy, it comes back with the "old" code when I build.

Thanks for your patience... I feel dumb.

**Comment by jedib0t** [comment]
Tag: https://github.com/jedib0t/go-pretty/releases/tag/v6.3.7

**Comment by jedib0t** [comment]
> @jedib0t , this might seem a bit of a stupid question, but remember, this is about my first full-fledged GO software.
> 
> How do I go about removing earlier versions of `github.com/jedib0t/go-pretty/v6` from go.mod ? I've erased go.{mod,sum} and $HOME/go/pkg/, go mod init vmman3, go mod tidy, it comes back with the "old" code when I build.
> 
> Thanks for your patience... I feel dumb.

Hey! Don't feel bad. `go mod` is not straightforward... Try using the following command:
```
go get github.com/jedib0t/go-pretty/v6@v6.3.7
```

This should fix go.mod to have just one version of go-pretty, and a `go mod tidy` should clean up your go.sum file.

**Comment by jeanfrancoisgratton** [comment]
Well, I was expecting the update to show up before you tagged the version, so I _was_ a bit dumb :)

Changed v6.3.6 to v6.3.7 in go.mod once you tagged the repo, go mod tidy, go build and here we go, I can confirm the fix.
Thanks for the quick replies+fix.
