### ISSUE TITLE
How to set html table border

### ISSUE THREAD

**Issue by kcmvp** [jedib0t/go-pretty#227]
**Is your feature request related to a problem? Please describe.**

I want to set border for a html table, here is what I am doing

```
	ct := table.Table{}
	ct.SetTitle("Lint Issues Report")
	style := table.StyleDefault
	style.Options.SeparateRows = true
	style.Options.DrawBorder = true
	style.HTML.CSSClass = table.DefaultHTMLCSSClass
	ct.SetStyle(style)
```

but I found the out html table does not have border(same effect as traditional way 'border=1')
and the output html file does not contains a **style** section

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kcmvp** [comment]
`ct := table.Table{}
	ct.SetTitle("Lint Issues Report")
	style := table.StyleDefault
	style.Options.SeparateRows = true
	style.Options.SeparateRows = true
	style.Options.DrawBorder = true
	style.HTML.CSSClass = table.DefaultHTMLCSSClass
	ct.SetStyle(style)`

**Comment by kcmvp** [comment]
it does not support html table with border or I wrongly use the api?

**Comment by jedib0t** [comment]
Hello! You need to use CSS for this. The table generated will have a "class" associated with it, and you should be able to customize it using CSS. `Style().Options.DrawBorder` controls console output and not HTML. HTML sytling will have to be enforced using CSS.

For example:
```golang
package main

import (
	"fmt"

	"github.com/jedib0t/go-pretty/v6/table"
)

func main() {
	ct := table.Table{}
	ct.AppendHeader(table.Row{"Filename", "Line Number", "Issue"})
	ct.AppendRow(table.Row{"foo/main.go", "5", "Use camelCase for variable names"})
	ct.SetTitle("Lint Issues Report")
	ct.Style().Options.SeparateRows = true
	ct.Style().Options.DrawBorder = true
	ct.Style().HTML.CSSClass = "foo_table"
	fmt.Println(ct.RenderHTML())
}
```

Output:
```html
<table class="foo_table">
  <caption class="title">Lint Issues Report</caption>
  <thead>
  <tr>
    <th>Filename</th>
    <th>Line Number</th>
    <th>Issue</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>foo/main.go</td>
    <td>5</td>
    <td>Use camelCase for variable names</td>
  </tr>
  </tbody>
</table>
```

In the above, the class on the table has been set to `foo_table`. You should be able to customize it using CSS like below:
```css
.foo_table {
   border: 3px double green;
   border-right-style: dashed;
   border-left-width: 17px;
   border-bottom-color: orange;
}
.foo_table tr {
   /* <tr> specific rules go here... */
}
```

**Comment by kcmvp** [comment]
Thank you very much! You mean I need a separated css file? And save it in the same folder with the generated html file?

**Comment by jedib0t** [comment]
> Thank you very much! You mean I need a separated css file? And save it in the same folder with the generated html file?

The table html is not the entire HTML file anyway. So you can have the CSS in the same file or separate, it is up to you.

The point being you style the HTML table yourself using CSS but it is an one time effort since you style it based on HTML tags and not based on the content.

**Comment by kcmvp** [comment]
got it. thank you! I think it's great to hook the output method write the css string to the html. at least give use a choice.

**Comment by jedib0t** [comment]
The colors on table rows/columns will be set as classes defined here: https://github.com/jedib0t/go-pretty/blob/main/text/color_html.go. So use nested classes to define how you want colors to appear in HTML.
