### ISSUE TITLE
Border color when title is used

### ISSUE THREAD

**Issue by alajmo** [jedib0t/go-pretty#234]
**Describe the bug**
No way to set border style for title.

**To Reproduce**

```go
package main

import (
    "os"

    "github.com/jedib0t/go-pretty/v6/text"
    "github.com/jedib0t/go-pretty/v6/table"
)

func main() {
    t := table.NewWriter()
    t.SetOutputMirror(os.Stdout)
    t.AppendHeader(table.Row{"#", "First Name", "Last Name", "Salary"})
    t.AppendRows([]table.Row{
        {1, "Arya", "Stark", 3000},
        {20, "Jon", "Snow", 2000, "You know nothing, Jon Snow!"},
    })
    t.AppendSeparator()
    t.AppendRow([]interface{}{300, "Tyrion", "Lannister", 5000})
    t.AppendFooter(table.Row{"", "", "Total", 10000})
    t.SetTitle("title test")
    t.Style().Title.Colors = text.Colors{text.Faint}
    t.Style().Color = table.ColorOptions{
		Header: text.Colors{text.Faint},
		Row: text.Colors{text.Faint},
		RowAlternate: text.Colors{text.Faint},
		Footer: text.Colors{text.Faint},
    }

    t.Render()
}

```

**Expected behavior**
I expect to be able to color the top portion of the border.

**Screenshots**
![border](https://user-images.githubusercontent.com/5246600/194255448-55a04a68-d6df-467d-9001-6d654799b492.png)

**Software (please complete the following information):**
 - OS: `Linux 5.18.0-2-amd64 Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux`
 - GoLang Version: `go version go1.18 linux/amd64`

**Comment by jedib0t** [comment]
Ack. This solution for this is part of the solution for #218. Will leave this open just for tracking.

**Comment by jedib0t** [comment]
Hey @alajmo ... the other feature may not see the light of the day. So I've delivered a fix for your issue and cut a tag for your use: https://github.com/jedib0t/go-pretty/releases/tag/v6.4.2

**Comment by alajmo** [comment]
Thank you, works wonderfully :)
