### ISSUE TITLE
column looks unresponsive

### ISSUE THREAD

**Issue by JinoArch** [jedib0t/go-pretty#235]
I am facing an issue where the column tables doesn't looks responsive. Not sure which property auto aligns columns

For example, when I use terminal in full screen it shows me expected output (shown below) and when I try to minimise terminal tab it gives sample output (shown below)

In the below the **remark** column outputs is more multiline.  Would like to know If any property is there where the the output is more/less than the resolution of terminal it automatically adjusts and goes to next line without setting column width

Sample Output:
╔════════════╦═══════════════════════════╦════════╦════════════════════════════════════════════════════╗
║ COMPONENTS ║ TESTS                     ║ STATUS ║ REMARK                                             ║
╠════════════╬═══════════════════════════╬════════╬════════════════════════════════════════════════════╣
║ ASG        ║ Subnet Check              ║ WARN   ║ Only 1 Subnet Found: subnet-0dererker323245. Nee ║
║            ║ (eks-xxxxxxxxxx ║        ║ ded min 3                                          ║
║            ║ cxxxxx)         ║        ║

Expected output : (used t.SetColumnConfigs)
<img width="849" alt="Screenshot 2022-10-16 at 7 06 45 PM" src="https://user-images.githubusercontent.com/39610834/196038462-0d9a3a1c-49ea-4f1c-97e2-f5e08baf82f6.png">

**Comment by jedib0t** [comment]
@JinoArch this is a function of the terminal. There's only so many characters that can be shown in a line. Terminals will try to wrap lines to fit the window size when you reduce the terminal size. There is nothing this library can do to overcome this. Depending on the terminal program you use, you may be able to force the terminal to NOT wrap the lines.
