### ISSUE TITLE
Background color of last row continues to bottom border of table

### ISSUE THREAD

**Issue by rhysd** [jedib0t/go-pretty#248]
**Describe the bug**

Background color of last row unexpectedly continues to the bottom border of rendered table. See the repro below.

**To Reproduce**

```go
package main

import (
	"os"

	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/jedib0t/go-pretty/v6/text"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"Hello"})
	t.AppendRow(table.Row{"World"})
	t.SetStyle(table.StyleRounded)
	t.Style().Color.Row = text.Colors{text.Reset, text.BgHiBlack}
	t.Render()
}
```

**Expected behavior**
Only the "World" row is highlighted with `BgHiBlack`.

**Screenshots**
<img width="81" alt="image" src="https://user-images.githubusercontent.com/823277/208425234-dced8955-48f3-49ad-9beb-f2887ed73663.png">

As you see, the highlighted color continues in bottom border of table `╰───────╯`

**Software (please complete the following information):**
 - OS: macOS 11.7
 - GoLang Version 1.19

**Additional context**

I at first saw this issue in https://github.com/google/osv-scanner and noticed the issue happened in this package.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/823277/208425565-a1176d12-a9ff-4769-aefe-ed2db7825d45.png">

**Comment by jedib0t** [comment]
This is a known issue. I'd probably have to change the code to skip coloring the separators altogether, but it may look uglier than this. :( Do you want to try coloring the columns individually using ColumnConfig.Colors instead of t.Style().Color.Row?

**Comment by rhysd** [comment]
@jedib0t Thanks for confirming that. I could not find any other issue ticket tracking this. Should I leave this issue open or close?

**Comment by jedib0t** [comment]
I meant I know of this issue. 😊 Sorry for the confusion.

Leave it open if the workaround doesn't satisfy you. I'll see if I can skip coloring all the separators instead.

**Comment by jedib0t** [comment]
@rhysd I've cut a tag for you with an option to turn off coloring borders and separators: https://github.com/jedib0t/go-pretty/releases/tag/v6.4.4

**Comment by rhysd** [comment]
@jedib0t Thank you! I'll have a look.

**Comment by rhysd** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/823277/211517383-fedda749-b88a-4fe8-8e59-1496e8ff22c1.png">

I confirmed. Thank you again.
