### ISSUE TITLE
align issue when set max width for non-ascii char

### ISSUE THREAD

**Issue by silver-chard** [jedib0t/go-pretty#251]
wrong align for non-ascii char like chinese

```golang
package main

import (
	"os"

	"github.com/jedib0t/go-pretty/v6/table"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendRows([]table.Row{
		{1, "Arya", "Stark", 3000},
		{20, "Jon", "Snow", 2000, "You know nothing, Jon Snow! "},
	})
	t.AppendSeparator()
	t.AppendRow([]interface{}{300, "Tyrion", "Lannister大人", 5000, "狮氏石室拭屎时食矢逝世，尸蚀，始失势"})
	t.SetColumnConfigs([]table.ColumnConfig{{Number: 5, WidthMax: 10}})
	t.Render()
}

```

![image](https://user-images.githubusercontent.com/9633121/210515017-68180708-ff71-4add-b9a4-7308221624fa.png)

**Comment by jedib0t** [comment]
I'm afraid this is an issue that cannot be fixed in this library. The way non-English characters are printed and the rendered width of these characters on a Console are beyond the scope of this library and can vary for every different terminal application and the font used.
