### ISSUE TITLE
Color for autoindex

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [jedib0t/go-pretty#252]
Hi,
I have applied rowPainter for coloring rows based on particular value. I have also used autoIndexing. The color applied for row is not applied on Autoindexed numbers. Can you please check?
![image](https://user-images.githubusercontent.com/102787031/210952531-e90d5429-832f-44ee-90a7-3997ca77fe76.png)

**Comment by jedib0t** [comment]
This is intentional. Just like the headers are not colors, the auto-indexed columns are also not colored.

If you want to color the index column, you can try using `table.Style().Colors.IndexColumn` (of course this does not do conditional coloring like row-painter does).
