### ISSUE TITLE
Specify row color on table.AppendRow

### ISSUE THREAD

**Issue by beihaifeiwu** [jedib0t/go-pretty#262]
```bash
 NAME     DIFF  ERR 
  a                  0    1              <- red 
  b                  0    0             <- green
  c                  0    0             <- green
```
I hope table.AppendRow  can specify color styles, which has high priority over table.Style()

**Comment by jedib0t** [comment]
Hey. You can always color the text before calling AppendRow. That will always have the highest priority.
```golang
table.AppendRow(table.Row{text.FgRed.Sprint("red")})
```

Or use `table.SetRowPainter()` to conditionally color the rows based on any column value.

**Comment by beihaifeiwu** [comment]
oh, thanks very much
