### ISSUE TITLE
Header autoMerge bug

### ISSUE THREAD

**Issue by fasnow** [jedib0t/go-pretty#264]
when use:
t.AppendHeader(table.Row{ip, ip}, table.RowConfig{AutoMerge: true})
t.SetStyle(table.StyleLight)
then:
![image](https://github.com/jedib0t/go-pretty/assets/40886524/fb2e73d8-94fe-4167-997d-e5a564030c61)

and more table.Row{ip, ip,ip,ip,ip,ip.....} then more space
![image](https://github.com/jedib0t/go-pretty/assets/40886524/324832f7-2e62-4651-9675-40e353179fd7)

**Comment by jedib0t** [comment]
Can you share the text you are using for the header?

**Comment by fasnow** [comment]
> Can you share the text you are using for the header?

It is not a fixed value, but an ip address derived from my program's input, such as 10.0.0.10

**Comment by beihai0xff** [comment]
same issue.
When I use table.RowConfig{AutoMerge: true} and set style table.StyleLight, 

```go
package main

import (
	"os"

	"github.com/jedib0t/go-pretty/v6/table"
)

func main() {
	rowConfigAutoMerge := table.RowConfig{AutoMerge: true}

	t := table.NewWriter()
	t.AppendHeader(table.Row{"Node", "Node", "Node", "Cluster", "Cluster", "Cluster", "Cluster"}, rowConfigAutoMerge)
	t.AppendHeader(table.Row{"IP", "Priority", "Role", "Addr", "Stratum", "State", "Offset"})
	t.SetAutoIndex(true)
	t.SetOutputMirror(os.Stdout)
	t.SetStyle(table.StyleLight)
	t.Style().Options.SeparateRows = true
	t.Render()
}
```
<img width="620" alt="image" src="https://github.com/jedib0t/go-pretty/assets/47047644/a129425a-2165-4d6c-967f-1ffce42c9b74">

**Comment by jedib0t** [comment]
Thanks for the sample code to reproduce the bug. I'm currently traveling - so give me some time to look into this.

**Comment by jedib0t** [comment]
Hey @beihai0xff ... I tried running your sample code and I couldn't reproduce the bug:

<img width="532" alt="image" src="https://github.com/jedib0t/go-pretty/assets/38574447/fc1be846-783d-414f-95ce-c7eb80aa7510">


I also tried it on go.dev/play to ensure it wasn't an environment issue: https://go.dev/play/p/bMyq8YPaFiH

<img width="1102" alt="image" src="https://github.com/jedib0t/go-pretty/assets/38574447/83bef5bc-d709-487d-b34b-771fb1824928">


Can you share information about your environment? Are you using the latest version of golang and this library?

**Comment by beihai0xff** [comment]
> Hey @beihai0xff ... I tried running your sample code and I couldn't reproduce the bug:
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/38574447/254464848-fc1be846-783d-414f-95ce-c7eb80aa7510.png">
> I also tried it on go.dev/play to ensure it wasn't an environment issue: https://go.dev/play/p/bMyq8YPaFiH
> 
> <img alt="image" width="1102" src="https://user-images.githubusercontent.com/38574447/254464995-83bef5bc-d709-487d-b34b-771fb1824928.png">
> Can you share information about your environment? Are you using the latest version of golang and this library?

```bash
➜  test go run main.go
┌───┬────────────────────────┬───────────────────────────────────────┐
│   │           NODE           │                  CLUSTER                 │
│   ├──────┬──────────┬──────┼─────────┬─────────┬─────────┬─────────┤
│   │   IP │ PRIORITY │ ROLE │    ADDR │ STRATUM │   STATE │  OFFSET │
├───┼──────┼──────────┼──────┼─────────┼─────────┼─────────┼─────────┤
└───┴──────┴──────────┴──────┴─────────┴─────────┴─────────┴─────────┘
➜  test go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/admin/Library/Caches/go-build"
GOENV="/Users/admin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/admin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/admin/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.5/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/admin/workspace/test/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jw/4jy3w2c175x9jtmm017zsbz80000gn/T/go-build2184315690=/tmp/go-build -gno-record-gcc-switches -fno-common"
➜  test cat go.mod
module test

go 1.20

require github.com/jedib0t/go-pretty/v6 v6.4.6

require (
	github.com/mattn/go-runewidth v0.0.13 // indirect
	github.com/rivo/uniseg v0.2.0 // indirect
	github.com/stretchr/testify v1.8.2 // indirect
	golang.org/x/sys v0.7.0 // indirect
)

**Comment by beihai0xff** [comment]
my os information:
```bash
bash-3.2$ uname -a
Darwin bogon 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64
```
It is really strange, I try to run the code on iterm2 and mac terminal, with bash, sh, zsh, all of above can reproduce the bug. but if I run the code on goland terminal (use zsh), the table looks good.

<img width="1312" alt="image" src="https://github.com/jedib0t/go-pretty/assets/47047644/88d32bde-7f86-4df4-832d-fd43e4c2c8fa">

**Comment by jedib0t** [comment]
Here is the code running on my iTerm2:
<img width="624" alt="image" src="https://github.com/jedib0t/go-pretty/assets/38574447/d1b4d751-5d23-44dc-a3bd-fd1491979733">

I'm running go1.19.4 on the latest version of go-pretty. Same output on bash/iTerm2 too.

I'm on an Intel MacBook though - don't think it should make a difference.

**Comment by jedib0t** [comment]
Try finding what font is being used in GoLand terminal, and try using the same on iTerm2?

**Comment by jedib0t** [comment]
Closing issue due to lack of response.
