### ISSUE TITLE
Table header separator

### ISSUE THREAD

**Issue by vadim-frosting** [jedib0t/go-pretty#265]
Is it possible to print a customized separator for the table header? For example customizing "StyleLight" with "=" as the separator character for the header, compared to "-" as non-header row separator

**Comment by jedib0t** [comment]
Yes, this seems to be a popular request. Duplicate of #218.

Real-life is getting in the way of me implementing this feature at the moment. Will try to get to this soon.

**Comment by jedib0t** [comment]
If you are still interested, I finally got this done with #386. Available for use in tag [v6.7.4](https://github.com/jedib0t/go-pretty/releases/tag/v6.7.4).
