### ISSUE TITLE
Cursor is moved while monitor progress in windows terminal

### ISSUE THREAD

**Issue by JHNX** [jedib0t/go-pretty#268]
**Describe the bug**
User progress feature to monitor some status in multiple rows
The cursor is moved and information is dumped disorderly if scroll screen

**To Reproduce**
Monitor progress status in multiple rows
Scroll screen
Check dumped information

**Expected behavior**
Status information shall be dumped in order like in Linux terminal

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: [Windows]
 - GoLang Version [1.20]

**Additional context**
N/A

**Comment by jedib0t** [comment]
Closing as duplicate of #269.

**Comment by JHNX** [comment]
Please take care of that #269 occurs in both Linux and Windows OS.
This issue occurs while moving cursor manually in Windows only.
