### ISSUE TITLE
Progress - dump disorderly if the number of items to be monitored is bigger than the lines of one screen

### ISSUE THREAD

**Issue by JHNX** [jedib0t/go-pretty#269]
**Describe the bug**
Use progress to monitor multiple status. If the number of items to be monitor is bigger than the lines of one screen, progress status is dumped disorderly.

**To Reproduce**
Set the number of trackers be bigger than the lines of one screen
Start monitor status
status information is dumped disorderly

**Expected behavior**
Progress can support monitor items more than one screen.

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: [Linux/Windows]
 - GoLang Version [1.20]

**Additional context**
N/A

**Comment by jedib0t** [comment]
I think I understand your request. This would need constant polling of the window width, and adjust the message/tracker sizes as needed. Might take some time to get done.

**Comment by JHNX** [comment]
Hi @jedib0t, please consider adjust to both width and height of the window. And do you have a plan when to enhance it?

**Comment by jedib0t** [comment]
Hey @JHNX ... the code in https://github.com/jedib0t/go-pretty/releases/tag/v6.5.1 trims the line output to fix the terminal width. The default behavior is to trim the output length, so you don't have to do any new coding apart from importing the latest version in your go.mod. Please test and let me know.

Terminal height is a little more complex to support, and I'll look into adding support in the future.
