### ISSUE TITLE
Go get github.com/jedib0t/go-pretty/v6  have a problem

### ISSUE THREAD

**Issue by sealandsigh** [jedib0t/go-pretty#275]
**Describe the bug**
go build github.com/jedib0t/go-pretty/v6: no non-test Go files in /xxx/xxxx/Documents/goproject/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.4.7

**To Reproduce**
go build github.com/jedib0t/go-pretty/v6: no non-test Go files in /xxx/xxxx/Documents/goproject/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.4.7

**Expected behavior**
go get ok

**Software (please complete the following information):**
 - OS: [e.g. macos]
 - GoLang Version [e.g. 1.17]

**Comment by jedib0t** [comment]
Hey @sealandsigh ... There is nothing to `build` in `go-pretty`.

```
$ go mod init
go: creating new go.mod: module github.com/jedib0t/test

$ go get -u github.com/jedib0t/go-pretty/v6@v6.4.7
go: added github.com/jedib0t/go-pretty/v6 v6.4.7
```
