### ISSUE TITLE
Markdown table row with multiline string adds <br/>

### ISSUE THREAD

**Issue by dkirrane** [jedib0t/go-pretty#278]
When I add it to a row and render the table markdonw I end up with `<br/>` in the row output.

```

	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	// t.SetOutputMirror(markdownFileWriter)
	t.AppendHeader(table.Row{"Code"})
	t.AppendSeparator()

	codeBlockMarkdown := "\n```" +
		`
			func message(s string) string {
				return s
			}
		` + "\n```"

	t.AppendRow([]interface{}{codeBlockMarkdown})

	t.RenderMarkdown()
```

Is there a way to prevent this and just print the multiline string without `<br/>`?
I'm trying to output a Markdown code block formatted with backticks.

```
| Code |
| --- |
| <br/>```<br/>            func message(s string) string {<br/>                return s<br/>            }<br/>        <br/>``` |
```

**Comment by jedib0t** [comment]
I don't believe most Markdown Table parsers/formats support multi-line cells. If you want multi-line content, esp formatted content like above, a Markdown Table may be the wrong container. Ref.: https://stackoverflow.com/questions/57165371/wrap-long-lines-in-markdown-tables

Can you show a raw Markdown Table with multi-line content like in your example?

**Comment by jedib0t** [comment]
Closing due to lack of response. Please feel free to reopen if you have any information that can help.
