### ISSUE TITLE
Github lacks enthusiasm reports, which would be necessary with your go-pretty!!! Absolutely fantastic!!!

### ISSUE THREAD

**Issue by Barpfotenbaer** [jedib0t/go-pretty#286]
About 20 years ago, I built something similar to go-pretty with PHP, but it wasn't nearly as extensive and nowhere near as cool as go-pretty! Today I was in the need to reimplement this functionality to build complex html-tables with go. I'm so glad I looked for an alternative beforehand and found your software. go-pretty is great!!! Thank you very much!!!  👍👣😆👍

**Comment by jedib0t** [comment]
Sorry for responding late... holidays and all. Thanks for the words of encouragement! ❤️
