### ISSUE TITLE
Calling SetRowPainter() will not compile

### ISSUE THREAD

**Issue by jlanzarotta** [jedib0t/go-pretty#297]
Hello,

I am not sure if this is bug or not... but for some reason calling SetRowPainter() does not compile.  I am using go 1.22.0 and go-pretty v6.5.4.

I am able to render a table just fine.  It was when I add the call to t.SetRowPainter(), that does not compile.  Here is a screenshot...

![image](https://github.com/jedib0t/go-pretty/assets/5437686/f2d9322e-cb8f-4e42-a57f-f3f554d7a934)

This code snippet does was taken from another example I found that was supposed to be working.

Any ideas?

Thanks,

**Comment by jedib0t** [comment]
Can you try following the example here: https://github.com/jedib0t/go-pretty/blob/main/table/render_test.go#L872-L881 ?

My IDE with golang 1.21.3 doesn't show any issues:
![image](https://github.com/jedib0t/go-pretty/assets/38574447/e811e61f-5bb4-477d-ba08-c306802a3bd8)

I'll try 1.22.0 shortly.

**Comment by jedib0t** [comment]
It works with go 1.22.1 too: https://play.golang.com/p/65kYWlAx4nm --- it may be an IDE issue at your end?

![image](https://github.com/jedib0t/go-pretty/assets/38574447/1a1636e5-7e52-4be3-bd84-a6e1a22a61a9)

**Comment by jlanzarotta** [comment]
Hello, thanks for the response.  It ended up being that I had an incorrect import.  Instead of having `"github.com/jedib0t/go-pretty/v6/text"`, I had `"github.com/jedib0t/go-pretty/text"`.
