### ISSUE TITLE
Automerge does not work in HTML rendered by table

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [jedib0t/go-pretty#298]
**Describe the bug**
The automerge used on certain columns of a table is not applied on HTML rendering. 

**To Reproduce**
Create table and apply automerge to some column. 
Render HTML for it. 

**Expected behavior**
Automerge should be applied in HTML view also.

**Screenshots**
![image](https://github.com/jedib0t/go-pretty/assets/102787031/475d247a-b39e-4063-9689-f98e1ea86c2c)
Above is the table rendered on console. As you can see, the first column is auto-merged. And below is the HTML code generated.
```
<tr>
    <td align="right">21</td>
    <td class="fg-green">CustomResources TestSuite</td>
    <td class="fg-green">Check Service Monitors</td>
    <td class="fg-green">Pass</td>
  </tr>
  <tr>
    <td align="right">22</td>
    <td class="fg-green">CustomResources TestSuite</td>
    <td class="fg-green">Check Pod Monitors</td>
    <td class="fg-green">Pass</td>
  </tr>
  <tr>
    <td align="right">23</td>
    <td class="fg-green">CustomResources TestSuite</td>
    <td class="fg-green">Check Probes</td>
    <td class="fg-green">Pass</td>
  </tr>
  <tr>
    <td align="right">24</td>
    <td class="fg-green">CustomResources TestSuite</td>
    <td class="fg-green">Check Service Monitors</td>
    <td class="fg-green">Pass</td>
```

**Software (please complete the following information):**
 - OS:Ubuntu
 - GoLang Version [e.g. 1.21]

**Additional context**
![image](https://github.com/jedib0t/go-pretty/assets/102787031/03a8e622-6bfc-44c0-9784-1e08e687e022)
I want to use `table.RenderHTML()` to write the content to a HTML file. When I render this file in browser, no styles are applied (see above screenshot). Obviously its because CSS classes such as `fg-green`, `fg-red` etc are not available. Can you please provide a correct example how to get this working correctly?

**Comment by jedib0t** [comment]
Hello @naveenbharadwaj-nc --- as noted in comments @ https://github.com/jedib0t/go-pretty/blob/main/table/config.go#L25-L34 ... auto-merge is not supported in CSV/HTML/MarkDown modes. I may implement this as a functionality that works in any mode in the future, but for now it is not. Sorry!

**Comment by naveenbharadwaj-nc** [comment]
I think it should be added in documentation rather than being as a comment in code.
Could you please help with another question about CSS?

**Comment by jedib0t** [comment]
You should be attaching a style sheet to your HTML on how you'd want the browser to render those classes.

For example:
```css
.fg-green {
    color: Chartreuse;
}
.fg-red {
    color: DarkRed;
}
.fg-blue {
    color: #0000cc;
}
```

You'd want to nest it under a selector or another class to make sure this is not globally applied - if that is a constraint.

**Comment by naveenbharadwaj-nc** [comment]
Thank you.
