### ISSUE TITLE
Automatic right alignment of number-cells only when number in each row

### ISSUE THREAD

**Issue by Skeeve** [jedib0t/go-pretty#299]
**Is your feature request related to a problem? Please describe.**
Automatical right-align of numbers works, as long as there are no "empty" cells in the column.

**Describe the solution you'd like**
It would be great if empty cells, i.e. those with an empty string, wouldn't count when determining the alignment.

**Describe alternatives you've considered**
Alternatively I thought a `nil` could count as a really empty cell, but that's printed as `<nil>` and the automatic right-alignment is lost.

**Additional context**
example on the playground: https://play.golang.com/p/NzekcPm1llN

**Comment by jedib0t** [comment]
Currently right-align can be enabled or forced using the `SetColumnConfigs(...)` interface. Auto-detection is designed to work only when all rows in a column contain numbers. Assuming <nil> or empty strings to be numeric may break existing behavior and is not worth it when there is a well-defined way to achieve the required alignment.

Feel free to chime in if you really think this is required despite the presence of `SetColumnConfigs(...)`.

**Comment by Skeeve** [comment]
Yes, I feel it is required, as I, in my use case, do not know, whether or not all of the values are numeric.

Keeping track of that is duplicate work, as your library already scans each column.

Maybe it's an option to have a new ColumnConfig property "EmptyNumeric" or something like that which will switch on this behavior?

**Comment by Skeeve** [comment]
> Yes, I feel it is required, as I, in my use case, do not know, whether or not all of the values are numeric.
> 
> Maybe it's an option to have a new ColumnConfig property "EmptyNumeric" or something like that which will switch on this behaviour?

I just emplemented exactly that. Maybe take a look?

**Comment by jedib0t** [comment]
Give me some time to think about this. `EmptyNumeric` does not sound right for some reason.

**Comment by Skeeve** [comment]
I'm happy with any name as long as the functionality is there. My first idea was „IgnoreEmpty“. 

As I said: having to keep track of the non-numericality would be duplicate work.

On the other hand: Excel automatically aligns cell-wise, not column-wise. Maybe that's an option too for your library:

```go
ColumnConfig{ Align: text.AutoCell }
```

So in a mixed-type column numbers would be right aligned and text left.
