### ISSUE TITLE
How to print table in the middle terminal

### ISSUE THREAD

**Issue by FerdinaKusumah** [jedib0t/go-pretty#310]
This is a wonderful library to print table using go, 

I Wonder how to print table in the middle of terminal ?
is there any style that handle this case ?

Thank you in advance.

**Comment by jedib0t** [comment]
Hey thanks for the compliment! Appreciate it very much! ❤️

The kind of functionality needed to position text in a terminal is out of scope of this library.

You may want to look into one of the many TUI (terminal-UI) libraries out there like:
* https://github.com/charmbracelet/bubbletea
* https://github.com/rivo/tview
