### ISSUE TITLE
Merging not all possible cells in a row

### ISSUE THREAD

**Issue by alexanius** [jedib0t/go-pretty#314]
Hi! Wonderful package!

I try to make table, where not all of equal cells in a row should be merged.

What do we have now:

```
AppendRow([]interface{}{"Debug info", "Debug info", "Yes", "Yes", ""}, rowConfigAutoMerge)


| Debug info                  | yes                  |     |
```

What do I want to get:

```
| Debug info                  | yes      | yes        |     |
```

Probably it should be something like column config, but for row. Where we can set the columns in a row, that should be merged:

```
rowConfigAutoMerge := table.RowConfig
    {Number:    1,
     AutoMerge: true,
     Align:     text.AlignLeft,
     VAlign:    text.VAlignMiddle}})
```

Are there any plans to implement such feature?

**Comment by jedib0t** [comment]
At this point of time there is no support planned for selective auto merge. The auto merge code is not at the right shape for such fine grained control.

**Comment by jedib0t** [comment]
You can probably try making one of the "Yes" values as "Yes " (with a space at the end) to work around the problem and prevent the auto-merge.
