### ISSUE TITLE
Display in incrementation

### ISSUE THREAD

**Issue by jeff06** [jedib0t/go-pretty#324]
**Describe the solution you'd like**
Display x number of lines at a time after pressing enter.

**Additional context**
Lets say i have 100 elements to show in a table. Currently with the .Render(), it display everything at once. I would like to display the header and the first 20 lines. When i press enter, it display the next 20 lines and so on. That way it doesnt just show everything at once.

Thanks,

**Comment by jeff06** [comment]
Ive decide that i could make this change. It sems that i cannot commit to a feature branch. Do you accepte pull request?

**Comment by jedib0t** [comment]
> Ive decide that i could make this change. It sems that i cannot commit to a feature branch. Do you accepte pull request?

Yes PR is the way to go for this repo.

**Comment by jeff06** [comment]
It doesn't seems like i can push. Can you add me as a contributer please?

**Comment by jedib0t** [comment]
The way you contribute is to fork the repo, push the commit to your fork and then open a PR from that fork.

**Comment by jeff06** [comment]
Thank you : https://github.com/jedib0t/go-pretty/pull/325
