### ISSUE TITLE
[Feature Request || Question] - Table - Clickable Results

### ISSUE THREAD

**Issue by ondrovic** [jedib0t/go-pretty#326]
**Is your feature request related to a problem? Please describe.**
No really a problem, not sure it even can be done

**Describe the solution you'd like**
Using Table I would find it helpful if you somehow make it so the rows are clickable,  I know you can open a file using

```
import "os/exec"
exec.Command(`explorer`, `/select,`, `File.txt`)
```

But for example
![image](https://github.com/user-attachments/assets/014314b9-d259-4fc4-89ed-b861ab204dd6)

I so I am thinking I would love it if somehow you could click the directory path and it would open. This might be way out of the scope of the table tool, since it would almost need to register some type of callback action to handle the clicks

**Describe alternatives you've considered**
None yet

**Additional context**

**Comment by jedib0t** [comment]
Maybe this is what you want: text/hyperlink.go

**Comment by ondrovic** [comment]
> Maybe this is what you want: text/hyperlink.go

Ill give it a try and see

**Comment by ondrovic** [comment]
found another solution using another package ;-)

**Comment by jedib0t** [comment]
Can you share it here for posterity?

**Comment by ondrovic** [comment]
sure "github.com/logrusorgru/aurora/v4" is  the package

```
in my case they are both set to the dir column
aurora.Hyperlink(label, link),
```
It does allow for doing the ctrl+click and open (although there is some formatting issues, which I am trying to figure out still)

![image](https://github.com/user-attachments/assets/1eb59b91-1380-48d4-8cd5-6888f72572c9)

![image](https://github.com/user-attachments/assets/f9c23f82-d756-47ba-9a18-afbb65dec672)


Update:

Even using the default `text.Htyperlink(dir, dir)` as provided results in alignment issues

```go
for _, result := range results.([]types.EntryResults) {
     dir = commonFormatters.FormatPath(result.Directory, runtime.GOOS)
     t.AppendRow(table.Row{
          text.Hyperlink(dir, dir),
	  result.FileName,
	  result.FileSize,
    })
}
```

![image](https://github.com/user-attachments/assets/425e49e1-80a7-4df9-abb4-8234cfe5b699)
![image](https://github.com/user-attachments/assets/3f5b1b7b-ebfb-4457-b97f-b0471eadfa9b)
