### ISSUE TITLE
How to apply text alignment to all header columns?

### ISSUE THREAD

**Issue by hellt** [jedib0t/go-pretty#340]
I love my table header row to have center-aligned text, like this

```
╭───┬──────┬──────────────┬──────────────────────────────┬───────────────┬─────────┬────────────────┬──────────────────────╮
│ # │ Name │ Container ID │             Image            │      Kind     │  State  │  IPv4 Address  │     IPv6 Address     │
├───┼──────┼──────────────┼──────────────────────────────┼───────────────┼─────────┼────────────────┼──────────────────────┤
│ 1 │ srl  │ 7faefde8ee2e │ ghcr.io/nokia/srlinux:latest │ nokia_srlinux │ running │ 172.20.20.2/24 │ 3fff:172:20:20::2/64 │
╰───┴──────┴──────────────┴──────────────────────────────┴───────────────┴─────────┴────────────────┴──────────────────────╯
```

The problem is, that it seems setting the text alignment of the header columns is only possible with 

```
table.SetColumnConfigs()
```

which needs to know either the column names, or indexes. I compile the table dynamically, so I might now know the names of the rows ahead of time.

At the same time, it seems there is no `table.AddColumnConfigs()` that would not overwrite the slice of column configs. How could I dynamically add the column config iterating over the slice of `table.Row`?

**Comment by jedib0t** [comment]
Is the list of columns dynamic or the number of columns fixed?

**Comment by jedib0t** [comment]
Hey @hellt ... with the linked PR that has been merged, you should be able to set up the default alignment you want on the rows/headers/footers. Sample usage is in the description of the PR. Note that Column-configs will override these values.

Use the "main" branch code and let me know if this works, and I'll cut a tag for you.

**Comment by hellt** [comment]
thanks for a quick turnover, @jedib0t 
this worked great! Looking forward for a tagged release 👍 

<img width="579" alt="image" src="https://github.com/user-attachments/assets/1ffc1934-33ed-4998-b619-f9a762a587e2">

**Comment by jedib0t** [comment]
Here you go: https://github.com/jedib0t/go-pretty/releases/tag/v6.6.2
