### ISSUE TITLE
Set background/foreground colors by row

### ISSUE THREAD

**Issue by Issif** [jedib0t/go-pretty#77]
Hi,

Really nice package, easy to use and direct csv/html outputs are great.

I would like to change color row, didn't see anything related. My purpose is to set a background in red if a specific = X, green if Y, etc.

Same idea with html export, It could specify class for rows.

Regards,

**Comment by jedib0t** [comment]
Thanks for the feedback!

Sounds like the feature I listed in the [TODO](https://github.com/jedib0t/go-pretty/blob/master/table/README.md#todo) a long time back:
* Generic Cell Content Transformers (with some ready-made ones)
   * Base64 Decoder
   * Currency Formatter
   * UnixTime to Date & Time
   * Status Formatter (color "FAILED" in RED, etc.)

Will get working on this soon.

**Comment by jedib0t** [comment]
Hey @Issif ... I've a usable implementation in the branch `column-config`. Can you try it and let me know if this is what you are looking for? The final implementation may be different, but I'd love to hear feedback on how it is right now.

Sample code to format the contents of a column like a currency: https://github.com/jedib0t/go-pretty/blob/column-config/table/render_test.go#L361-L366 -- this test uses all the functionality provided by ColumnConfig -- you may want to just set the `Name`/`Number` and `Formatter`.

Here is ColumnConfig in all its glory: https://github.com/jedib0t/go-pretty/blob/column-config/table/config.go#L9

I have a feeling this is a little too drastic a change.

**Comment by Issif** [comment]
Thanks. 

If I understand correctly your code, we can add a function for modifying text/number by column, it means a function that will be applied on each cell of the column. For coloring the whole row, we need to add a function, that will set fore/background with same colors but considering a value from another cell, not current one. Your example shows how to make string replacement but I don't get how to change color.

Regards,

**Comment by jedib0t** [comment]
So, using the `Formatter`, you'll get access to the cell value which can be modified/colored/etc. at render-time. Something like:

Here is an example to format a Salary column that contains integer values:
```go
tw.SetColumnConfigs([]ColumnConfig{{
    Name: "Salary",
    Formatter: text.Formatter(func(val interface{}) string { // val here is the value of a single cell as set using AppendRow
        if valInt, ok := val.(int); ok {
            color := text.FgGreen
            if valInt < 0 {
                color = text.FgRed
            }
            return color.Sprintf("$ %d", valInt)
        }
        // fallback in case the value is not an integer
        return fmt.Sprint(val)
    }),
}
```

This approach right now does not give you access to the other cells in the row, or let you set the background on the entire cell (works only on the text contents). WDYT?

**Comment by Issif** [comment]
It works for colors. I agree that coloring the whole cell, not only the background of text, could be tricky.

![image](https://user-images.githubusercontent.com/4520100/57553854-18bbc100-7370-11e9-8d01-a696836bb68b.png)

It seems text alignments are lost, see the code I use for my test :

```
package main

import (
	"fmt"
	"os"

	"github.com/jedib0t/go-pretty/table"
	"github.com/jedib0t/go-pretty/text"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"ID", "NAME", "STATUS"})
	t.AppendRows([]table.Row{
		{1, "Customer1", "red"},
		{2, "Customer2", "green"},
		{3, "Customer3", "green"},
		{4, "Customer4", "yellow"},
	})
	t.SetAlign([]text.Align{text.AlignCenter, text.AlignCenter, text.AlignCenter})
	t.SetVAlign([]text.VAlign{text.VAlignMiddle, text.VAlignMiddle, text.VAlignMiddle})
	t.SetColumnConfigs([]table.ColumnConfig{{
		Name: "STATUS",
		Formatter: text.Formatter(func(val interface{}) string { // val here is the value of a single cell as set using AppendRow
			if _, ok := val.(string); ok {
				var color text.Color
				switch val {
				case "red":
					color = text.BgRed
				case "yellow":
					color = text.BgYellow
				case "green":
					color = text.BgGreen
				}
				return color.Sprintf("%s", val)
			}
			// fallback in case the value is not an integer
			return fmt.Sprint(val)
		}),
	}})
	t.Render()
	t.SetStyle(table.StyleColoredBright)
	t.Render()
}
```

As `table.rows = []rows = []string`, maybe we could pass to `Formatter` function the "coordinates" of cell, cell 3 in row 14 for example. This could let us select the value from another cell, `t.rows[14][2]`, what do you think?

**Comment by jedib0t** [comment]
The alignment is incorrect because the code cannot handle the old and new style of instructions. It will be aligned correctly if you use ColumnConfig.Align instead of SetAlign(). Like so:
```go
	tw.SetColumnConfigs([]ColumnConfig{{
		Name:   "ID",
		Align:  text.AlignCenter,
		VAlign: text.VAlignMiddle,
	}, {
		Name:   "NAME",
		Align:  text.AlignCenter,
		VAlign: text.VAlignMiddle,
	}, {
		Name: "STATUS",
		Align:  text.AlignCenter,
		VAlign: text.VAlignMiddle,
		Formatter: text.Formatter(func(val interface{}) string { // val here is the value of a single cell as set using AppendRow
			if _, ok := val.(string); ok {
```

So I'm debating between two options:

A simple new function `SetFormatters` which doesn't impact any of the existing functions:
```go
t.SetAlign([]text.Align{text.AlignDefault, text.AlignLeft, text.AlignRight, text.AlignDefault})
t.SetVAlign([]text.Align{text.VAlignTop, text.VAlignDefault, text.VAlignMiddle, text.VAlignDefault})
t.SetColors([]text.Colors{nil, nil, {text.FgRed, text.Bold}, nil})
t.SetFormatters([]text.Formatter{nil, nil, salaryFormatter, nil})
```
Which makes it super backward compatible but hard to manage when you have too many columns.

Or a new function that replaces a bunch of existing ones:
```go
// no more t.SetAlign()
// no more t.SetVAlign()
// no more t.SetColors()
t.SetColumnConfigs([]table.ColumnConfigs{{
    Name: "First Name",
    VAlign: text.VAlignTop,
}, {
    Name: "Last Name",
    Align: text.AlignLeft,
}, {
    Name: "Salary",
    Align: text.AlignRight,
    VAlign: text.VAlignMiddle,
    Colors: text.Colors{text.FgRed, text.Bold},
    Formatter: salaryFormatter,
}})
```
Which makes the column's properties very obvious and readable, but kills backward compatibility. Folks using the new version will have to change the function calls whenever I remove the old deprecated functions.

Which one would you choose if you had a choice?

I also get your point about the formatter having access to a lot more than just the cell's contents. Will try to come up with a better signature for the formatter so you can access the entire Row.

**Comment by Issif** [comment]
Thanks for the tip, your package is so full of (great) features, it helps a lot to have this kind of examples.

I totally agree that current functions are annoying when we have a lot of columns and less readable

A new way to do so, like the function you propose, is a good idea for me, more readable, more controls. We can add your new `Formatter` that transforms value inside the cell, but we could also imagine a `CellFormatter` that could make possible what I had in mind by creating this issue, a render like this :

![image](https://user-images.githubusercontent.com/4520100/57574790-bcc06d80-743f-11e9-8a96-62405a4d1d0f.png)

**Comment by jedib0t** [comment]
Thanks for the feedback.

That render does look good - will try to find a way to make it work.

**Comment by jedib0t** [comment]
Hey @Issif, I've just pushed one more commit on the same branch and have added the following interface to Table:
```go
// RowPainter is a custom function that takes a Row as input and returns the
// text.Colors{} to use on the entire row
type RowPainter func(row Row) text.Colors

// Writer declares the interfaces that can be used to setup and render a table.
type Writer interface {
...
    SetRowPainter(painter RowPainter)
...
}
```

Here is a unit-test that uses the interface to format entire rows: https://github.com/jedib0t/go-pretty/blob/column-config/table/render_test.go#L515-L523 -- please note that this will color all the cells in the row except for the index column set using `SetAutoIndex` or `SetIndexColumn`.

Can you try it and let me know if this works for you?

**Comment by Issif** [comment]
You rock !

![image](https://user-images.githubusercontent.com/4520100/57624063-68c59e00-7591-11e9-8885-d63d7c10eff8.png)

````go
package main

import (
	"os"

	"github.com/jedib0t/go-pretty/table"
	"github.com/jedib0t/go-pretty/text"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"ID", "NAME", "STATUS"})
	t.SetAlignHeader([]text.Align{text.AlignCenter, text.AlignCenter, text.AlignCenter})
	t.AppendRows([]table.Row{
		{1, "Customer1", "red"},
		{2, "Customer2", "green"},
		{3, "Customer3", "green"},
		{4, "Customer4", "yellow"},
	})
	t.SetColumnConfigs([]table.ColumnConfig{
		{
			Name:   "ID",
			VAlign: text.VAlignMiddle,
			Align:  text.AlignCenter,
		},
		{
			Name:   "NAME",
			VAlign: text.VAlignMiddle,
			Align:  text.AlignCenter,
		},
		{
			Name:   "STATUS",
			VAlign: text.VAlignMiddle,
			Align:  text.AlignCenter,
		},
	})
	t.SetRowPainter(table.RowPainter(func(row table.Row) text.Colors {
		switch row[2] {
		case "green":
			return text.Colors{text.BgGreen, text.FgBlack}
		case "yellow":
			return text.Colors{text.BgYellow, text.FgBlack}
		case "red":
			return text.Colors{text.BgRed, text.FgBlack}
		}
		return nil
	}))
	t.Render()
	t.SetStyle(table.StyleColoredBright)
	t.Render()
}
````

Will try it on a real program, a small tool to list our on-call users from PagerDuty. Will show you result right after.

**Comment by Issif** [comment]
It's perfect, here the new output for my little tool, exactly what I wanted, current on-call lines are green (we are 3 teams, with a line for Business Hours Only (HO) and another for Non-Business-Hours (HNO), non colored lines are next shedules :

![image](https://user-images.githubusercontent.com/4520100/57634170-0f676a00-75a5-11e9-9ad0-5469deff014a.png)

(I obfuscated my colleagues' names, just kept mine)

**Comment by jedib0t** [comment]
Awesome. Now that it works, I'll clean-up the code a bit and cut a new tag in a day or two.

BTW, you might want to use `ColumnConfig.AlignHeader` instead of `SetAlignHeader()` just to not have to make changes in the future.

**Comment by Issif** [comment]
@jedib0t I don't want to abuse your kindness but is that possible to add this behavior to `RenderHTML()` ? Thanks.

**Comment by jedib0t** [comment]
Will definitely try to.

**Comment by jedib0t** [comment]
Sorry for the lack of updates. Will try to get this out this weekend.

**Comment by Issif** [comment]
don't worry, it's not urgent. thanks

**Comment by jedib0t** [comment]
@Issif I've supported coloring the cells in RenderHTML() using CSS classes based on whatever you set using SetRowPainter() or ColumnConfig.Colors* or SetColors*(). The CSS classes are nested, so you can define your own styles like `.go-pretty-table .fg-red {color: #FF4500}` and it should work. Can you try it out and let me know if this works for you?

Sample output:
```html
<table class="go-pretty-table">
  <thead>
  <tr>
    <th align="right" class="bg-white fg-black">#</th>
    <th class="bg-white fg-black">First Name</th>
    <th class="bg-white fg-black">Last Name</th>
    <th align="right" class="bg-white fg-black">Salary</th>
    <th class="bg-white fg-black">&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td align="right" class="bold">1</td>
    <td class="fg-cyan">Arya</td>
    <td class="fg-magenta">Stark</td>
    <td align="right" valign="bottom" class="fg-yellow">3000</td>
    <td valign="bottom" class="fg-black">&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="bold">20</td>
    <td class="fg-cyan">Jon</td>
    <td class="fg-magenta">Snow</td>
    <td align="right" valign="bottom" class="fg-yellow">2000</td>
    <td valign="bottom" class="fg-black">You know nothing, Jon Snow!</td>
  </tr>
  <tr>
    <td align="right" class="bold">300</td>
    <td class="fg-cyan">Tyrion</td>
    <td class="fg-magenta">Lannister</td>
    <td align="right" valign="bottom" class="fg-yellow">5000</td>
    <td valign="bottom" class="fg-black">&nbsp;</td>
  </tr>
  <tr>
    <td align="right" class="bold">0</td>
    <td class="fg-cyan">Winter</td>
    <td class="fg-magenta">Is</td>
    <td align="right" valign="bottom" class="fg-yellow">0</td>
    <td valign="bottom" class="fg-black">Coming.<br/>The North Remembers!<br/>This is known.</td>
  </tr>
  </tbody>
  <tfoot>
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td class="bg-white fg-black">Total</td>
    <td align="right" class="bg-white fg-black">10000</td>
    <td>&nbsp;</td>
  </tr>
  </tfoot>
</table>
```

Note that I force-pushed to the branch `column-config` and wiped out some previous commits. Functionality remains the same though.

**Comment by Issif** [comment]
Hi,

I got a `panic` :
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func1(0xc0001b6e40, 0x3, 0x3, 0xc00005f860, 0xa21440, 0x7f4640230008)
        /mnt/c/Users/thomas.labarussias/Golang/pagerdutyOnCall/tt.go:42 +0x191
github.com/jedib0t/go-pretty/table.(*Table).initForRenderRowsStringify(0xc0000e4b00, 0xc00005f7a0, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc00025e000, 0xc00023ecc8, ...)
        /home/thomas/go/pkg/mod/github.com/jedib0t/go-pretty@v4.0.4-0.20190529101452-a507b80e8af2+incompatible/table/table.go:613 +0x1b5
github.com/jedib0t/go-pretty/table.(*Table).initForRenderRows(0xc0000e4b00)
        /home/thomas/go/pkg/mod/github.com/jedib0t/go-pretty@v4.0.4-0.20190529101452-a507b80e8af2+incompatible/table/table.go:587 +0xbb
github.com/jedib0t/go-pretty/table.(*Table).initForRender(0xc0000e4b00)
        /home/thomas/go/pkg/mod/github.com/jedib0t/go-pretty@v4.0.4-0.20190529101452-a507b80e8af2+incompatible/table/table.go:511 +0xa8
github.com/jedib0t/go-pretty/table.(*Table).RenderHTML(0xc0000e4b00, 0x78ab88, 0x3)
        /home/thomas/go/pkg/mod/github.com/jedib0t/go-pretty@v4.0.4-0.20190529101452-a507b80e8af2+incompatible/table/render_html.go:59 +0x40
main.main()
        /mnt/c/Users/thomas.labarussias/Golang/pagerdutyOnCall/tt.go:56 +0x46e
exit status 2
```
Here the code for reproduce :

```go
package main

import (
	"os"

	"github.com/jedib0t/go-pretty/table"
	"github.com/jedib0t/go-pretty/text"
)

func main() {
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"ID", "NAME", "STATUS"})
	t.AppendRows([]table.Row{
		{1, "Customer1", "red"},
		{2, "Customer2", "green"},
		{3, "Customer3", "green"},
		{4, "Customer4", "yellow"},
	})
	t.SetAlign([]text.Align{text.AlignCenter, text.AlignCenter, text.AlignCenter})
	t.SetVAlign([]text.VAlign{text.VAlignMiddle, text.VAlignMiddle, text.VAlignMiddle})
	// t.SetColumnConfigs([]table.ColumnConfig{{
	// 	Name: "STATUS",
	// 	Formatter: text.Formatter(func(val interface{}) string { // val here is the value of a single cell as set using AppendRow
	// 		if _, ok := val.(string); ok {
	// 			var color text.Color
	// 			switch val {
	// 			case "red":
	// 				color = text.BgRed
	// 			case "yellow":
	// 				color = text.BgYellow
	// 			case "green":
	// 				color = text.BgGreen
	// 			}
	// 			return color.Sprintf("%s", val)
	// 		}
	// 		// fallback in case the value is not an integer
	// 		return fmt.Sprint(val)
	// 	}),
	// }})
	t.SetRowPainter(table.RowPainter(func(row table.Row) text.Colors {
		switch row[3].(string) {
		case "red":
			return text.Colors{text.BgRed, text.FgBlack}
		case "yellow":
			return text.Colors{text.BgYellow, text.FgBlack}
		case "green":
			return text.Colors{text.BgGreen, text.FgBlack}
		}
		return nil
	}))

	// t.Render()
	// t.SetStyle(table.StyleColoredBright)
	// t.Render()
	t.RenderHTML()
}
```
I use `go mod` for dependencies with your last commit : `github.com/jedib0t/go-pretty v4.0.4-0.20190529101452-a507b80e8af2+incompatible`

**Comment by jedib0t** [comment]
Found 2 bugs. One in your code and one in mine. The one you want to fix is in the switch statement here:
```golang
	t.SetRowPainter(table.RowPainter(func(row table.Row) text.Colors {
		switch row[3].(string) {
		case "red":
```
Change it to `switch row[2].(string)`.

I've fixed the other bug I found in my code: https://github.com/jedib0t/go-pretty/commit/fa92d46815e9d6e82176328a7941f691cf1e0bd9

With the fixes:
```html
<table class="go-pretty-table">
  <thead>
  <tr>
    <th align="right">ID</th>
    <th>NAME</th>
    <th>STATUS</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td align="center" class="bg-red fg-black" valign="middle">1</td>
    <td align="center" class="bg-red fg-black" valign="middle">Customer1</td>
    <td align="center" class="bg-red fg-black" valign="middle">red</td>
  </tr>
  <tr>
    <td align="center" class="bg-green fg-black" valign="middle">2</td>
    <td align="center" class="bg-green fg-black" valign="middle">Customer2</td>
    <td align="center" class="bg-green fg-black" valign="middle">green</td>
  </tr>
  <tr>
    <td align="center" class="bg-green fg-black" valign="middle">3</td>
    <td align="center" class="bg-green fg-black" valign="middle">Customer3</td>
    <td align="center" class="bg-green fg-black" valign="middle">green</td>
  </tr>
  <tr>
    <td align="center" class="bg-yellow fg-black" valign="middle">4</td>
    <td align="center" class="bg-yellow fg-black" valign="middle">Customer4</td>
    <td align="center" class="bg-yellow fg-black" valign="middle">yellow</td>
  </tr>
  </tbody>
</table>
```

**Comment by Issif** [comment]
Thanks for both bug fixes, I thought have seen a shift in index key before, the row ids started at 1 and not 0. My bad. Sorry.

After your fix and a little bit of css : 
![image](https://user-images.githubusercontent.com/4520100/58562433-877e9280-8229-11e9-95ae-1ef03a30f643.png)

Great ! Thanks.

**Comment by jedib0t** [comment]
Will update documentation and cut a release in a day or two.

**Comment by jedib0t** [comment]
Hey @Issif ... thanks for your feedback. I've cut a new release `v4.2.0` with the above fixes: https://github.com/jedib0t/go-pretty/releases/tag/v4.2.0

**Comment by Issif** [comment]
Thanks again for your help.

Here a tool I just released that uses these new features : https://github.com/claranet/go-s3-describe

**Comment by jedib0t** [comment]
Wow. Looks cool!
