### ISSUE TITLE
Potential unicode issue with tables/padding

### ISSUE THREAD

**Issue by Dids** [jedib0t/go-pretty#78]
**Describe the bug**
The table formatting and padding worked brilliantly, until unicode characters were added to the mix, which seems to have broken the padding.

**To Reproduce**
See screenshot.

**Expected behavior**
I was half expecting this to be handled automagically, and while I'm not even sure if it's doable within the context of this library, I'd very much prefer to see it work.

**Screenshots**
![Imgur](https://i.imgur.com/KkEzxgq.png)

**Software (please complete the following information):**
 - OS: macOS Mojave
 - GoLang Version 1.12

**Comment by jedib0t** [comment]
Thanks for reporting the bug!

I'll try to fix this soon.

**Comment by jedib0t** [comment]
Hwy @Dids --- it looks like this rendering issue is not easy to solve and has a strong dependency on the typeface that is used in the Console/Terminal. However, I've started using https://github.com/mattn/go-runewidth to calculate the rune width, and it should render better than before (but is not 100% right):

Before:
```
+--------------+
| NAME         |
+--------------+
| Arya Stark ツ |
| Jon Snow     |
| Tyrion       |
| ¯\_(⊙︿⊙)_/¯  |
+--------------+
```

After:
```
+---------------+
| NAME          |
+---------------+
| Arya Stark ツ |
| Jon Snow      |
| Tyrion        |
| ¯\_(⊙︿⊙)_/¯  |
+---------------+
```

If you find a better more accurate method of calculating the width, please share it here.

**Comment by Dids** [comment]
@jedib0t Thank you very much! I figured it was a long shot, but happy to hear that you found a solution so quickly. :)

Any chance of a new tag/release for this?

**Comment by jedib0t** [comment]
Yes. Will cut a new patch release in an hour or two.

Update: here you go: https://github.com/jedib0t/go-pretty/releases/tag/v4.0.3
