### ISSUE TITLE
Is it possible to use two headers with different colors ?

### ISSUE THREAD

**Issue by mydockergit** [jedib0t/go-pretty#86]
I have the following code:  
```
package main
import(
	"github.com/jedib0t/go-pretty/table"
	"os"
)


func main (){
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"A", "B", "C"})
	t.AppendRow([]interface{}{"Arya          a", "Stark       a", "You know    a"})
	t.SetStyle(table.StyleColoredBright)
	t.Render()
}
```  
It prints the following table:  
![image](https://user-images.githubusercontent.com/37586216/61851307-3bfe0300-aebf-11e9-8204-2c332dc95543.png)

I wanted to add another header on the above table but with different color, that it will appear like that:  
![image](https://user-images.githubusercontent.com/37586216/61851385-7c5d8100-aebf-11e9-9e6d-8b4d34577dc8.png)

This is what I tried to do:   
```
package main
import(
	"fmt"
	"github.com/jedib0t/go-pretty/table"
	"github.com/jedib0t/go-pretty/text"
	"os"
	"strings"
)
func main (){
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"A", "B", "C"})
	t.AppendRow([]interface{}{"Arya          a", "Stark       a", "You know    a"})
	t.SetStyle(table.StyleColoredBright)

	result := t.Render()
	tableStrLines := strings.Split(result, "\n")
	titleLine := []rune(tableStrLines[0])

	fmt.Printf("%s%s" , text.BgMagenta.EscapeSeq(), text.FgBlack.EscapeSeq())
	header1 := fmt.Sprintf("Game of Thrones: %s", "hola")
	for len(header1) < len(titleLine) {
		header1 += " "
	}
	fmt.Println(header1 + "\n") 
	fmt.Printf("%s%s" , text.BgBlack.EscapeSeq(), text.FgWhite.EscapeSeq())
}
```

But the problem is that it prints me the line below because I ran the `Render()` before I calculate the header length. Also it prints it with larger length although I calculate exactly how much it needs to be:  
![image](https://user-images.githubusercontent.com/37586216/61851559-fa218c80-aebf-11e9-9d6c-f3cb0088ed18.png)

Is there other way to do it ?

**Comment by mydockergit** [comment]
OK I found a workaround (calculating the rows length):  
```
package main
import(
	"fmt"
	"github.com/jedib0t/go-pretty/table"
	"github.com/jedib0t/go-pretty/text"
	"os"
)
func main (){
	t := table.NewWriter()
	t.SetOutputMirror(os.Stdout)
	t.AppendHeader(table.Row{"A", "B", "C"})
	
	first := "Arya          a"
	second := "Stark       a"
	third := "You know    a"
	t.AppendRow([]interface{}{first, second, third})
	t.SetStyle(table.StyleColoredBright)

	fmt.Printf("%s%s" , text.BgMagenta.EscapeSeq(), text.FgBlack.EscapeSeq())
	header1 := fmt.Sprintf("Game of Thrones: %s", "hola")
	for len(header1) < len(fmt.Sprintf("%s%s%s", first, second, third)) {
		header1 += " "
	}
	header1 += "      "
	fmt.Println(header1) 
	fmt.Printf("%s%s" , text.BgBlack.EscapeSeq(), text.FgWhite.EscapeSeq())
	t.Render()
}
```  

This is the result:  
![image](https://user-images.githubusercontent.com/37586216/61852070-39041200-aec1-11e9-8819-793d50677ea9.png)



Let me know if you have other option to do it with your library, if not, you can close this ticket.  
Thanks

**Comment by jedib0t** [comment]
Sounds like you want a "Title" row similar to the one asked in https://github.com/jedib0t/go-pretty/issues/85 --- I'm yet to get that done. Will update once that feature is ready.

**Comment by mydockergit** [comment]
Yes, but I also wanted the ability to control the title color.  
So I can create a table with two headers with different colors.  
Right now I am doing it manually.

**Comment by jedib0t** [comment]
Hey @mydockergit --- I just supported setting a title on a table, and styling it as necessary. Check out `tableWriter.SetTitle()` and `tableWriter.Style().Title`. It is used in some of the last few examples at https://github.com/jedib0t/go-pretty/tree/master/cmd/demo-table

It is now easy to get something like:
```
+---------------------------------------------------------------------+
| Game of Thrones                                                     +
+-----+------------+-----------+--------+-----------------------------+
|   # | FIRST NAME | LAST NAME | SALARY |                             |
+-----+------------+-----------+--------+-----------------------------+
|   1 | Arya       | Stark     |   3000 |                             |
|  20 | Jon        | Snow      |   2000 | You know nothing, Jon Snow! |
| 300 | Tyrion     | Lannister |   5000 |                             |
+-----+------------+-----------+--------+-----------------------------+
|     |            | TOTAL     |  10000 |                             |
+-----+------------+-----------+--------+-----------------------------+
```

As you wanted, the way it gets rendered can be customized using Style.Title: https://github.com/jedib0t/go-pretty/blob/master/table/style.go#L752-L757

Also check out the table colors demo by running `go run ./cmd/demo-table/demo.go colors` or look at https://github.com/jedib0t/go-pretty/blob/master/cmd/demo-table/demo-colors.png

Here is a single sample:
![Screenshot from 2019-07-26 16-57-15](https://user-images.githubusercontent.com/38574447/61986799-89b16300-afc6-11e9-87be-0a5a63108dbf.png)

**Comment by jedib0t** [comment]
One other way to get what you want is to wrap a table in another table. Just set the outer table's header style as needed and turn off the borders and separators on it.

**Comment by mydockergit** [comment]
Wow, looks amazing. Great job ! 
I will check it out.

**Comment by mydockergit** [comment]
Checked, works great.
Thanks
