### ISSUE TITLE
Is there a way to paint a specific row/column entry?

### ISSUE THREAD

**Issue by slnt** [jedib0t/go-pretty#91]
For example, I'd like to paint not a whole row but just a specific (row, column) entry in the table. Is this possible under the current API?

**Comment by slnt** [comment]
Nevermind, the things I want are very clearly in the `text` package!

**Comment by jedib0t** [comment]
You can also use the the SetRowPainter() interface as used here: https://github.com/jedib0t/go-pretty/blob/master/table/render_test.go#L517-L568

But this will paint the entire row and not just a single column.
