### ISSUE TITLE
Option to invert rows and columns

### ISSUE THREAD

**Issue by infalmo** [jedib0t/go-pretty#94]
Is it possible to add a feature to flip a table, such that the rows and columns are interchanged?
For example, table
```
-----------------------
| Header 1 | Header 2 |
-----------------------
| Data 1   | Data 2   |
-----------------------
| Data 3   | Data 4   |
-----------------------
```
should be flipped to
```
------------------------------
| Header 1 | Data 1 | Data 3 |
------------------------------
| Header 2 | Data 2 | Data 4 |
------------------------------
```

**Comment by infalmo** [comment]
Even if flipping is not possible, adding a completely new table configuration would be equally good.

**Comment by jedib0t** [comment]
This should be possible. But the way the code is structured currently, it may prove to be a little difficult with the coloring options. I'll look into this.

**Comment by lepasq** [comment]
Hi! I'd like to work on this issue.
My approach would be to add a method in table/table.go, which either simply swaps the contents of the columns and the rows, or which would create an entirely new table and then fill up the rows and columns invertedly. Is there anything that I should take into account, such as any side effects that could happen?

**Comment by jedib0t** [comment]
@lepasq Inverting is part of the task. The other would be to reconcile the styling, Column/Row configs, the sorting, etc. If you want to take a stab at it, please try. But I fear that until the current logic is changed to treat each cell as its own object with all the properties embedded in it, inverting it may be too difficult.

**Comment by jedib0t** [comment]
Closing this as I haven't been able to make any progress on this, and I haven't seen anyone else request for this feature. Please feel free to reopen if you feel otherwise.
