### ISSUE TITLE
Add option to clear table row content

### ISSUE THREAD

**Issue by infalmo** [jedib0t/go-pretty#95]
Adding a feature to clear table row content would help in outputting dynamic tables, as the rows tend to get overwritten

**Comment by jedib0t** [comment]
I'm not sure I understand this. Can you explain in a little more detail?

**Comment by infalmo** [comment]
Something like table.ClearRows() to delete all rows from the table. So if I have a table that updates it's contents after a particular interval of time, I need not reinitialise the table but instead just add rows to the table after clearing all previous rows.

Hope this was clear to you!

**Comment by jedib0t** [comment]
Oh yes this will be a useful feature. Will implement.

**Comment by jedib0t** [comment]
Hey @infixint943 ... hope the new interfaces work for you. The one you want is `ResetRows()`.
