### ISSUE TITLE
Add arbitrary separators to tables

### ISSUE THREAD

**Issue by guumaster** [jedib0t/go-pretty#97]
**Is your feature request related to a problem? Please describe.**
I would like to have the option to add a table row that is printed as a separator row. Like what happens with header and footer, but some way of programmatically add a new separator between any rows.

**Describe the solution you'd like**
Something like `AddSeparator()` to mark a line separator between rows.

**Describe alternatives you've considered**
-

**Additional context**
I'm trying to migrate my project [hostctl](https://github.com/guumaster/hostctl) to use `go-pretty` but this feature is needed to split content of each profile on the printed table.

**Comment by jedib0t** [comment]
I think I understand your ask here, but can you share an example of how you'd like the output to look like?

**Comment by jedib0t** [comment]
Never mind. I think this can be done. Will look into it.

**Comment by guumaster** [comment]
Something like this:

```
+-----+------------+-----------+--------+-----------------------------+
|   # | FIRST NAME | LAST NAME | SALARY |                             |
+-----+------------+-----------+--------+-----------------------------+
|   1 | Arya       | Stark     |   3000 |                             |
|  20 | Jon        | Snow      |   2000 | You know nothing, Jon Snow! |
+-----+------------+-----------+--------+-----------------------------+
| 300 | Tyrion     | Lannister |   5000 |                             |
+-----+------------+-----------+--------+-----------------------------+
|     |            | TOTAL     |  10000 |                             |
+-----+------------+-----------+--------+-----------------------------+
```
Marking the line between Jon and Tyrion as separator with some method call

**Comment by jedib0t** [comment]
Hey @guumaster, I've added support for appending Separator rows at will. However, please take a look at the caveats listed in the PR @ #101. The PR's description also contains sample code and output. Lemme know if this works, and if you need anything else.

Hope this helps! 👍

**Comment by guumaster** [comment]
This is great. Thank you very much. :+1:
